[[advanced-topics]]
= Дополнительные материалы

В этой главе рассматриваются темы, которые выходят за рамки вводного руководства, но часто полезны в реальной упаковке RPM.

[[Signing-Packages]]
== Подпись пакетов

Подпись пакета - это способ защитить пакет для конечного пользователя. Безопасная транспортировка может быть достигнута с помощью реализации протокола HTTPS. Такой метод используют, когда пакет загружается непосредственно перед установкой. Однако пакеты часто загружаются заранее и хранятся в локальных репозиториях перед их использованием. Пакеты подписываются, чтобы гарантировать, что никакая третья сторона не сможет изменить содержимое пакета.

Существует три способа подписи пакета:

* xref:Adding-a-Signature-to-a-Package[Добавление подписи к уже существующему пакету].

* xref:Replacing-a-Package-Signature[Замена подписи на уже существующем пакете].

* xref:Build-time-Signing[
Подпись пакета во время сборки].

[[Adding-a-Signature-to-a-Package]]
=== Добавление подписи к пакету

В большинстве случаев пакеты создаются без подписи. Подпись добавляется непосредственно перед выпуском пакета.

Чтобы добавить другую подпись к пакету, используйте опцию `--addsign`. Наличие более чем одной подписи позволяет зафиксировать путь владения пакетом от разработчика пакета до конечного пользователя.

В качестве примера подразделение компании создает пакет и подписывает его ключом подразделения. Затем штаб-квартира компании проверяет подпись пакета и добавляет корпоративную подпись к пакету, заявляя, что подписанный пакет является подлинным.

С двумя подписями пакеи попадает к продавцу. Продавец проверяет подписи и, если они проверяются, также добавляет свою подпись.

Теперь пакет отправляется в компанию, которая желает его развернуть. Проверив каждую подпись на упаковке, они знают, что это подлинная копия, не изменившаяся с момента её первого создания. В зависимости от внутреннего контроля внедряющей компании, они могут добавить свою собственную подпись, чтобы заверить своих сотрудников в том, что пакет получил их корпоративное одобрение.

Вывод из команды `--addsign`:

[source,bash]
----
$ rpm --addsign blather-7.9-1.i386.rpm
            Enter pass phrase:

Pass phrase is good.
blather-7.9-1.i386.rpm:
----

Для проверки подписей пакета с несколькими подписями:

[source,bash]
----
$ rpm --checksig blather-7.9-1.i386.rpm
blather-7.9-1.i386.rpm: size pgp pgp md5 OK
----

Два обозначения `pgp` в выходных данных команды `rpm --checksig` показывают, что пакет был подписан дважды.

RPM позволяет добавлять одну и ту же подпись несколько раз. Параметр `--addsign`
не проверяет наличие нескольких идентичных подписей.

[source,bash]
----
$ rpm --addsig blather-7.9-1.i386.rpm
              Enter pass phrase:

Pass phrase is good.
blather-7.9-1.i386.rpm:
$ rpm --addsig blather-7.9-1.i386.rpm
              Enter pass phrase:

Pass phrase is good.
blather-7.9-1.i386.rpm:
$ rpm --addsig blather-7.9-1.i386.rpm
              Enter pass phrase:

Pass phrase is good.
blather-7.9-1.i386.rpm:
$ rpm --checksig blather-7.9-1.i386.rpm
blather-7.9-1.i386.rpm: size pgp pgp pgp pgp md5 OK
----

На выходе команды `rpm --checksig` отображается четыре подписи.

[[Replacing-a-Package-Signature]]
=== Замена подписи пакета 

Чтобы изменить открытый ключ без необходимости пересобирать каждый пакет, используйте опцию `--resign`.

[source,bash]
----
$ rpm --resign blather-7.9-1.i386.rpm
            Enter pass phrase:

Pass phrase is good.
blather-7.9-1.i386.rpm:
----

Использование опции `--resign` с несколькими пакетами:

[source,bash]
----
$ rpm --resign b*.rpm
            Enter pass phrase:

Pass phrase is good.
blather-7.9-1.i386.rpm:
bother-3.5-1.i386.rpm:
----

[[Build-time-Signing]]
=== Подпись во время сборки

Чтобы подписать пакет во время сборки, используйте команду `rpmbuild` с параметром `--sign`. Для этого необходимо ввести кодовую фразу PGP.

Для примера:

[source,bash]
----
$ rpmbuild -ba --sign blather-7.9.spec
            Enter pass phrase:

Pass phrase is good.
* Package: blather
…
Binary Packaging: blather-7.9-1
Finding dependencies...
…
Generating signature: 1002
Wrote: /usr/src/redhat/RPMS/i386/blather-7.9-1.i386.rpm
…
Source Packaging: blather-7.9-1
…
Generating signature: 1002
Wrote: /usr/src/redhat/SRPMS/blather-7.9-1.src.rpm
----

Сообщение "Generating signature" появляется как в бинарном, так и в исходном разделах упаковки. Число, следующее за сообщением, указывает на то, что добавленная подпись была создана с использованием  PGP.

[NOTE]
--
При использовании опции `--sign` в `rpmbuild`, используйте только аргументы `-bb` или `-ba` для сборки пакета. Аргумент `-ba` обозначает сборку бинарных *и* исходных пакетов.
--

Чтобы проверить подпись пакета, используйте комманду `--checksig`. Для примера:

[source,bash]
----
$ rpm --checksig blather-7.9-1.i386.rpm
blather-7.9-1.i386.rpm: size pgp md5 OK
----

[[Building-Multiple-Packages]]
==== Сборка нескольких пакетов

При сборке нескольких пакетов используйте следующий синтаксис, чтобы избежать многократного ввода кодовой фразы
PGP. Например, при сборке пакетов `blather` и `bother`, подпишите их, следуя примеру ниже:

[source,bash]
----
$ rpmbuild -ba --sign b*.spec
              Enter pass phrase:

Pass phrase is good.
* Package: blather
…
Binary Packaging: blather-7.9-1
…
Generating signature: 1002
Wrote: /usr/src/redhat/RPMS/i386/blather-7.9-1.i386.rpm
…
Source Packaging: blather-7.9-1
…
Generating signature: 1002
Wrote: /usr/src/redhat/SRPMS/blather-7.9-1.src.rpm
…
* Package: bother
…
Binary Packaging: bother-3.5-1
…
Generating signature: 1002
Wrote: /usr/src/redhat/RPMS/i386/bother-3.5-1.i386.rpm
…
Source Packaging: bother-3.5-1
…
Generating signature: 1002
Wrote: /usr/src/redhat/SRPMS/bother-3.5-1.src.rpm
----



[[more-on-macros]]
== Подробнее о макросах

Существует множество встроенных макросов RPM, и мы рассмотрим некоторые из них в следующем разделе, однако исчерпывающий список можно найти на странице
https://rpm-software-management.github.io/rpm/manual/macros.html[RPM Official Documentation].

ifdef::community[]
Существуют также макросы, предоставляемые Вашим дистрибутивом
https://en.wikipedia.org/wiki/Linux[Linux], в этом разделе мы рассмотрим некоторые из них, предоставляемые https://getfedora.org/[Fedora],
https://www.centos.org/[CentOS] и
https://www.redhat.com/en/technologies/linux-platforms[RHEL], а также предоставим информацию о том, как проверить Вашу систему, чтобы узнать о других, которые мы не рассматриваем, или для их обнаружения в других дистрибутивах Linux на основе RPM
endif::community[]

ifdef::rhel[]
Существуют также макросы, предоставляемые Red Hat Enterprise Linux, некоторые из
которые мы рассмотрим в этом разделе. Мы также узнаем, как проверить вашу систему, чтобы узнать о других макросах.
endif::rhel[]

[[defining-your-own]]
=== Определение Ваших Собственных Макросов

Вы можете определить свои собственные макросы. Ниже приводится выдержка из
https://rpm-software-management.github.io/rpm/manual/macros.html[RPM Official Documentation],  в которой содержится исчерпывающая информация о возможностях макросов.

Чтобы определить макрос, используйте:

[source,specfile]
----
%global <name>[(opts)] <body>
----

Все пробелы, окружающие  ``\ ``, удаляются.  Имя может состоять из буквенно-цифровых символов и символа `_`,  и должно иметь длину не менее 3 символов. Макрос без поля `(opts)` является “простым” в том смысле, что выполняется только рекурсивное расширение макроса. Параметризованный макрос содержит поле `(opts)` field. The
`opts` - (строка в круглых скобках) передается точно так же, как и в getopt(3)  для обработки
argc/argv  в начале вызова макроса.

[NOTE]
--
Более старый SPEC файлы RPM могут использовать шаблон макроса `%define <name> <body>`. Различия между макросами `%define` и `%global` заключаются в следующем:

* `%define` имеет локальную область действия, что означает, что он применяется только к указанной части SPEC файла. Кроме того, тело макроса  `%define` расширяется при использовании.
* `%global` имеет глобальную область действия, что означает, что он применяется ко всему SPEC файлу.
Кроме того, тело макроса `%global` асширяется во время определения.
--

Пример:

----
%global githash 0ec4e58
%global python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
----

NOTE: Макросы всегда оцениваются, даже в комментариях. Иногда это безобидно. Но во втором примере мы выполняем команду python, чтобы получить содержимое макроса. Эта команда будет выполняться даже тогда, когда Вы закомментируете макрос, или когда Вы вводите имя макроса в %changelog. Чтобы закомментировать макрос, используйте 
`%%`. Например: `%%global`.

[[setup]]
=== %setup

Макрос  ``%setup`` можно использовать для сборки пакета с помощью tarball.
Стандартное поведение макроса ``%setup`` можно увидеть в выходных данных ``rpmbuild``.
В начале каждой фазы макрос выводит ``Executing(%something)``.
Например:

[source,bash]
----
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.DhddsG
----

Выходные данные оболочки устанавливаются с включенным ``set -x``. Чтобы просмотреть содержимое 
``/var/tmp/rpm-tmp.DhddsG``, используйте опцию ``--debug``, поскольку ``rpmbuild`` удаляет временные файлы после успешной сборки. Здесь отображается настройка переменных среды, например:

[source,bash]
----
cd '/builddir/build/BUILD'
rm -rf 'cello-1.0'
/usr/bin/gzip -dc '/builddir/build/SOURCES/cello-1.0.tar.gz' | /usr/bin/tar -xof -
STATUS=$?
if [ $STATUS -ne 0 ]; then
  exit $STATUS
fi
cd 'cello-1.0'
/usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
----

Макрос ``%setup`` гарантирует, что мы работаем в правильном каталоге, удаляет остатки предыдущих сборок, распаковывает исходный архив и устанавливает некоторые привилегии по умолчанию. Существует несколько вариантов настройки поведения макроса 
``%setup``.

[[setup-q]]
==== %setup -q

Параметр ``-q``  ограничивает детализацию макроса  ``%setup``. Вместо ``tar -xof`` выполняется только ``tar -xvvof``. Этот параметр должен быть использован в качестве первого.

[[setup-n]]
==== %setup -n

В некоторых случаях каталог из расширенного архива имеет другое имя, чем ожидалось ``%{name}-%{version}``. Это может привести к ошибке макроса ``%setup``.  Имя каталога должно быть указано параметром ``-n directory_name``.

Например, если имя пакета  ``cello``, но исходный код заархивирован в ``hello-1.0.tgz`` и содержит каталог ``hello/``, содержимое SPEC файла должно быть следующим:

[source,specfile]
----
Name: cello
Source0: https://example.com/%{name}/release/hello-%{version}.tar.gz
…
%prep
%setup -n hello
----

[[setup-c]]
==== %setup -c

Параметр  ``-c`` можно использовать, если архив исходного кода не содержит никаких подкаталогов и после распаковки файлы из архива заполняют текущий каталог. Опция ``-c`` создает каталог и переходит к расширению архива. Наглядный пример:

[source,bash]
----
/usr/bin/mkdir -p cello-1.0
cd 'cello-1.0'
----

Каталог не изменяется после расширения архива.

[[setup-dt]]
==== %setup -D и -T

Параметр ``-D``  отключает удаление каталога исходного кода. Этот параметр полезен, если макрос ``%setup`` используется несколько раз. По сути, параметр ``-D`` означает, что сделующие строки не используются:

[source,bash]
----
rm -rf 'cello-1.0'
----

Параметр``-T`` отключает расширение хранилища исходного кода, удаляя следующую строку из скрипта:

[source,bash]
----
/usr/bin/gzip -dc '/builddir/build/SOURCES/cello-1.0.tar.gz' | /usr/bin/tar -xvvof -
----

[[setup-ab]]
==== %setup -a и -b

Параметры ``-a`` и ``-b`` расширяют определённые источники.

* Параметр ``-b`` (расшифровывается как `before`) расширяет определенные источники перед входом в рабочий каталог.
* Параметр ``-a`` (расшифровывается как  `after`) расширяет эти источники после входа. Их аргументами являются исходные номера из преамбулы файла спецификации.

Например, допустим, что архив ``cello-1.0.tar.gz`` содержит пустой каталог ``examples``, и примеры поставляются в отдельных
``examples.tar.gz`` tarball архивах, и они разархивируются в каталог с тем же именем. В этом случае используйте ``-a 1``, так как мы хотим разархивировать ``Source1`` после входа в рабочий каталог:

[source,specfile]
----
Source0: https://example.com/%{name}/release/%{name}-%{version}.tar.gz
Source1: examples.tar.gz
…
%prep
%setup -a 1
----

Но если бы примеры были в отдельном ``cello-1.0-examples.tar.gz`` tarball архиве, который расширяется до ``cello-1.0/examples``, используйте параметры ``-b 1``, поскольку ``Source1`` должен быть разархивирован перед входом в рабочий каталог:

[source,specfile]
----
Source0: https://example.com/%{name}/release/%{name}-%{version}.tar.gz
Source1: %{name}-%{version}-examples.tar.gz
…
%prep
%setup -b 1
----

Вы также можете использовать комбинацию всех этих опций.

[[files]]
=== %files

Общие  “расширенные” макросы RPM, необходимые в разделе ``%files``:

[cols="20%,80%"]
|====
| Макрос             | Описание
| %license           | Макрос идентифицирует файл, указанный в списке, как файл ЛИЦЕНЗИИ, и он будет установлен и помечен как таковой RPM. Пример: ``%license LICENSE``
| %doc               | Этот макрос идентифицирует файл, указанный как документация, и он будет установлен и помечен RPM как таковой. Это часто используется не только для документации об упаковываемом программном обеспечении, но и для примеров кода и различных элементов, которые должны сопровождать документацию. Пример: ``%doc README``
| %dir               | Макрос указывает, что путь является каталогом, которым должен владеть этот RPM. Это важно, чтобы манифест RPM-файла точно знал, какие каталоги очищать при удалении. Пример: ``%dir %{_libdir}/%{name}``
| %config(noreplace) | Указывает, что следующий файл является файлом конфигурации и поэтому не должен перезаписываться (или заменяться) при установке или обновлении пакета, если файл был изменен по сравнению с исходной контрольной установкой. В случае внесения изменений файл будет создан с добавлением ``.rpmnew`` в конец имени файла при обновлении или установке, чтобы ранее существующий или измененный файл в целевой системе не был изменен. Пример: ``%config(noreplace) %{_sysconfdir}/%{name}/%{name}.conf``
|====

[[built-in-macros]]
=== Встроенные макросы

В Вашей системе есть много встроенных макросов RPM, и самый быстрый способ просмотреть их все - это просто выполнить команду ``rpm --showrc``. Обратите внимание, что это будет содержать много выходных данных, поэтому его часто используют в сочетании с каналом для `grep`.

Вы также можете найти информацию о макросах RPM, которые поставляются непосредственно с версией RPM Вашей системы, просмотрев выходные данные   ``rpm -ql rpm`` , обратив внимание на файлы с названием ``macros`` в структуре каталогов.  

[[rpm-distribution-macros]]
=== RPM Макросы, предоставляемые дистрибутивом

Различные дистрибутивы будут предоставлять разные наборы рекомендуемых макросов RPM в зависимости от языковой реализации упаковываемого программного обеспечения или конкретных рекомендаций рассматриваемого дистрибутива.

ifdef::community[]
Они часто предоставляются в виде самих пакетов RPM и могут быть установлены с помощью пакетного менеджера, такого как http://yum.baseurl.org/[yum] или
https://github.com/rpm-software-management/dnf[dnf]. Сами файлы макросов после установки можно найти в ``/usr/lib/rpm/macros.d/``, и они будут включены в вывод ``rpm --showrc`` по умолчанию после установки.
endif::community[]

ifdef::rhel[]
Они часто предоставляются в виде самих пакетов RPM и могут быть установлены с помощью пакетного менеджера, такого как http://yum.baseurl.org/[yum] или
https://github.com/rpm-software-management/dnf[dnf]. Сами файлы макросов после установки можно найти в ``/usr/lib/rpm/macros.d/``, и они будут включены в вывод ``rpm --showrc`` по умолчанию после установки.
endif::rhel[]

Одним из основных примеров этого является раздел
https://docs.fedoraproject.org/en-US/packaging-guidelines/[Fedora Packaging
Guidelines], относящийся конкретно к
https://docs.fedoraproject.org/en-US/packaging-guidelines/_domain_specific_guidelines[Application
Specific Guidelines], который на момент написания этой статьи содержит более 60 различных наборов руководств вместе с соответствующими наборами макросов RPM для упаковки.

ifdef::community[]
Одним из примеров такого рода RPM может быть https://www.python.org/[Python]
версии 2.x, и если у нас установлен пакет ``python2-rpm-macros`` 
(доступный в EPEL для RHEL 7 и CentOS 7), у нас есть ряд доступных, специфичных для python2 макросов.
endif::community[]

ifdef::rhel[]
Одним из примеров такого рода RPM может быть https://www.python.org/[Python]
версии 2.x, и если у нас установлен пакет ``python2-rpm-macros`` 
(доступный в EPEL для RHEL 7 и CentOS 7), у нас есть ряд доступных, специфичных для python2 макросов.
endif::rhel[]

[source,bash]
----
$ rpm -ql python2-rpm-macros
/usr/lib/rpm/macros.d/macros.python2

$ rpm --showrc | grep python2
-14: __python2  /usr/bin/python2
CFLAGS="%{optflags}" %{__python2} %{py_setup} %{?py_setup_args} build --executable="%{__python2} %{py2_shbang_opts}" %{?1}
CFLAGS="%{optflags}" %{__python2} %{py_setup} %{?py_setup_args} install -O1 --skip-build --root %{buildroot} %{?1}
-14: python2_sitearch   %(%{__python2} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(1))")
-14: python2_sitelib    %(%{__python2} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
-14: python2_version    %(%{__python2} -c "import sys; sys.stdout.write('{0.major}.{0.minor}'.format(sys.version_info))")
-14: python2_version_nodots     %(%{__python2} -c "import sys; sys.stdout.write('{0.major}{0.minor}'.format(sys.version_info))")

----

В приведенном выше выводе отображаются необработанные определения макросов RPM, но нас, вероятно, больше интересует, что мы можем сделать с помощью ``rpm --eval`` , чтобы определить, что они делают, а также как они могут быть полезны для нас при упаковке RPMs.

[source,bash]
----
$ rpm --eval %{__python2}
/usr/bin/python2

$ rpm --eval %{python2_sitearch}
/usr/lib64/python2.7/site-packages

$ rpm --eval %{python2_sitelib}
/usr/lib/python2.7/site-packages

$ rpm --eval %{python2_version}
2.7

$ rpm --eval %{python2_version_nodots}
27

----

[[custom-macros]]
== Пользовательские макросы

Вы можете переопределить макросы в файле ``~/.rpmmacros``. Любые внесенные вами изменения повлияют на каждую сборку на Вашем компьютере.

Существует несколько макросов, которые Вы можете использовать для переопределения::

``%_topdir /opt/some/working/directory/rpmbuild``:: Вы можете создать этот каталог, включая все подкаталоги, с помощью утилиты ``rpmdev-setuptree``.
Значение этого макроса по умолчанию равно``~/rpmbuild``.

``%_smp_mflags -l3``:: Этот макрос часто используется для передачи в Makefile, например: 
``make %{?_smp_mflags}``, и для задания количества одновременных процессов на этапе сборки. По умолчанию для него задано значение ``-jX``, где X - количество ядер. Если Вы измените количество ядер, Вы можете ускорить или замедлить сборку пакетов.

Хотя Вы можете определить любые новые макросы в файле ``~/.rpmmacros``  это не рекомендуется, поскольку эти макросы не будут присутствовать на других компьютерах, где пользователи могут захотеть попытаться пересобрать Ваш пакет.

[[epoch-scriptlets-and-triggers]]
== Epoch, Скриптлеты и Триггеры

В мире SPEC файлов RPM существуют различные разделы, которые считаются продвинутыми, поскольку они влияют не только на файл спецификации, способ сборки пакета, но и на конечный компьютер, на который устанавливается результирующий RPM. В этом разделе мы рассмотрим наиболее распространенные из них, такие как Epoch, Скриптлеты и триггеры.

[[epoch]]
=== Epoch

Первым в списке стоит ``Epoch``, epoch - это способ определения взвешенных зависимостей на основе номеров версий. Его значение по умолчанию равно 0, если директива ``Epoch``  не указана в SPEC файле. Это не рассматривалось в разделе "SPEC файл" этого руководства, потому что почти всегда вводить значени Epoch  - плохая идея, поскольку это искажает то, что вы обычно ожидаете от RPM при сравнении версий пакетов.

Например, если был установлен пакет ``foobar`` с ``Epoch: 1`` и ``Version: 1.0``, а кто-то другой упаковал ``foobar`` с``Version: 2.0`` , но просто опустил директиву ``Epoch`` либо потому, что они не знали о её необходимости, либо просто забыли, эта новая версия никогда не будет считаться обновлением, потому что версия Epoch превалирует над традиционным маркером
Name-Version-Release, который означает управление версиями для RPM-пакетов.

Этот подход обычно используется только в случае крайней необходимости для решения проблемы с порядком обновления, которая может возникнуть как побочный эффект программного обеспечения из upstream репозитория, изменяющего схемы нумерации версий или версии, включающие буквенные символы, которые не всегда можно надёжно сравнить на основе кодирование.

[[triggers-and-scriptlets]]
=== Скриптлеты и Триггеры

В пакетах RPM существует ряд директив, которые можно использовать для внесения необходимых или желаемых изменений в систему во время установки RPM. Они называются **скриптлеты**.

Один из основных примеров того, когда и почему Вы хотели бы это сделать,  это когда установлена системная служба RPM и она предоставляет 
https://freedesktop.org/wiki/Software/systemd/[systemd]
https://www.freedesktop.org/software/systemd/man/systemd.unit.html[файл].
Во время установки нам нужно будет уведомить
https://freedesktop.org/wiki/Software/systemd/[systemd]  о появлении нового модуля, чтобы системный администратор мог выполнить команду, аналогичную  ``systemctl start
foo.service`` после установки вымышленного ``foo`` (который в этом примере предоставляет демон). Аналогично, нам нужно было бы отменить это действие при деинсталляции, чтобы администратор не получал ошибок из-за того, что бинарный файл демона больше не установлен, но файл модуля все еще существует в запущенной конфигурации systemd.

Существует небольшая горстка распространенных скриптлетов, они похожи на “заголовки разделов”, такие как ``%build`` or ``%install``, в том смысле, что они определяются многострочными сегментами кода, часто написанными, как стандартный сценарий оболочки
ifdef::community[https://en.wikipedia.org/wiki/POSIX[POSIX]]
ifdef::rhel[POSIX]
, но могут быть на нескольких разных языках программирования.
Исчерпывающий список этих доступных языков можно найти в _Официальной документации RPM_.

Следующие скриптлеты:

[cols="20%,80%"]
|====
| Директива   | Описание
| ``%pre``    | Скриптлет, который выполняется непосредственно перед установкой пакета в целевую систему.
| ``%post``   | Скриптлет, который выполняется сразу после установки пакета в целевой системе.
| ``%preun``  | Скриптлет, который выполняется непосредственно перед удалением пакета из целевой системы.
| ``%postun`` | Скриптлет, который выполняется сразу после удаления пакета из целевой системы.
|====

Также часто для этой функции существуют макросы RPM.  В нашем предыдущем примере мы обсуждали необходимость получения  https://freedesktop.org/wiki/Software/systemd/[systemd]
уведомления о новом
https://www.freedesktop.org/software/systemd/man/systemd.unit.html[unit file],
, это легко обрабатывается макросами скриптлетов systemd, как Мы можем видеть из приведенного ниже примера вывода.  Более подробную информацию об этом можно найти в
https://fedoraproject.org/wiki/Packaging:Systemd[Fedora systemd Packaging
Guidelines].

[source,bash]
----
$ rpm --showrc | grep systemd
-14: __transaction_systemd_inhibit      %{__plugindir}/systemd_inhibit.so
-14: _journalcatalogdir /usr/lib/systemd/catalog
-14: _presetdir /usr/lib/systemd/system-preset
-14: _unitdir   /usr/lib/systemd/system
-14: _userunitdir       /usr/lib/systemd/user
/usr/lib/systemd/systemd-binfmt %{?*} >/dev/null 2>&1 || :
/usr/lib/systemd/systemd-sysctl %{?*} >/dev/null 2>&1 || :
-14: systemd_post
-14: systemd_postun
-14: systemd_postun_with_restart
-14: systemd_preun
-14: systemd_requires
Requires(post): systemd
Requires(preun): systemd
Requires(postun): systemd
-14: systemd_user_post  %systemd_post --user --global %{?*}
-14: systemd_user_postun        %{nil}
-14: systemd_user_postun_with_restart   %{nil}
-14: systemd_user_preun
systemd-sysusers %{?*} >/dev/null 2>&1 || :
echo %{?*} | systemd-sysusers - >/dev/null 2>&1 || :
systemd-tmpfiles --create %{?*} >/dev/null 2>&1 || :

$ rpm --eval %{systemd_post}

if [ $1 -eq 1 ] ; then
        # Initial installation
        systemctl preset  >/dev/null 2>&1 || :
fi

$ rpm --eval %{systemd_postun}

systemctl daemon-reload >/dev/null 2>&1 || :

$ rpm --eval %{systemd_preun}

if [ $1 -eq 0 ] ; then
        # Package removal, not upgrade
        systemctl --no-reload disable  > /dev/null 2>&1 || :
        systemctl stop  > /dev/null 2>&1 || :
fi

----

Еще один элемент, который обеспечивает еще более детальный контроль над транзакцией RPM в целом, - это то, что известно как **триггеры**. По сути, это то же самое, что и скриптлет, но выполняется в очень определенном порядке операций во время транзакции установки или обновления RPM, что позволяет более точно контролировать весь процесс.    

Порядок, в котором выполняется каждый из них, и подробная информация о котором - приведена ниже.

[source,specfile]
----
all-%pretrans
...
any-%triggerprein (%triggerprein from other packages set off by new install)
new-%triggerprein
new-%pre      for new version of package being installed
...           (all new files are installed)
new-%post     for new version of package being installed

any-%triggerin (%triggerin from other packages set off by new install)
new-%triggerin
old-%triggerun
any-%triggerun (%triggerun from other packages set off by old uninstall)

old-%preun    for old version of package being removed
...           (all old files are removed)
old-%postun   for old version of package being removed

old-%triggerpostun
any-%triggerpostun (%triggerpostun from other packages set off by old un
            install)
...
all-%posttrans

----

ifdef::community[]
Вышеуказанные элементы взяты из прилагаемой документации RPM, найденной в
``/usr/share/doc/rpm/triggers`` на системах Fedora и
``/usr/share/doc/rpm-4.*/triggers`` в системах RHEL 7 и CentOS 7.
endif::community[]

ifdef::rhel[]
Вышеупомянутые элементы взяты из включенной документации RPM, которую можно найти в
``/usr/share/doc/rpm-4.*/triggers``.
endif::rhel[]

[id="Using-Non-Shell-Scripts-in-spec-File"]
==== Использование скриптов без оболочки в SPEC файле

Параметр скриптлета `-p`, в SPEC файле позволяет вызывать определенный интерпретатор вместо стандартного `-p{nbsp}/bin/sh`. Наглядным примером является скрипт, который выводит сообщение после установки `pello.py`.

. Откройте файл `pello.spec`.

. Найдите следующую строку:
+
[source,specfile]
----
install -m 0644 %{name}.py* %{buildroot}/usr/lib/%{name}/
----
+
Под этой строкой вставьте следующий код:
+
[source,specfile]
----
%post -p /usr/bin/python3
print("This is {} code".format("python"))
----

. Создайте свой пакет в соответствии с главой xref:building-rpms[Сборка RPMS].

ifdef::community[]
. Установите Ваш пакет:
+
[source,bash]
----
# dnf install /home/<username>/rpmbuild/RPMS/noarch/pello-0.1.1-1.fc27.noarch.rpm
----
+
Результатом выполнения этой команды является следующее сообщение после установки:
+
[source]
----
Installing       : pello-0.1.1-1.fc27.noarch                              1/1
Running scriptlet: pello-0.1.1-1.fc27.noarch                              1/1
This is python code
----
endif::community[]

ifdef::rhel[]
. Install your package:
+
[source,bash]
----
# yum install /home/<username>/rpmbuild/RPMS/noarch/pello-0.1.1-1.fc27.noarch.rpm
----
+
The output of this command is the following message after the installation:
+
[source]
----
Installing       : pello-0.1.1-1.fc27.noarch                              1/1
Running scriptlet: pello-0.1.1-1.fc27.noarch                              1/1
This is python code
----
endif::rhel[]

[NOTE]
--
* Чтобы использовать скрипт  Python{nbsp}3: Напишите строку `%post -p /usr/bin/python3`  под строкой `install -m` in a SPEC file.

* Чтобы использовать скрипт Lua: Напишите строку `%post -p <lua>` под строкой
`install{nbsp}-m` в SPEC файле.

* Таким образом, в SPEC файле может быть указан любой интерпретатор. 
--

[[rpm-conditionals]]
== Условные обозначения RPM 

Условные обозначения RPM позволяют условно включать различные разделы SPEC файла.

Чаще всего условные обозначения имеют дело с:

* разделами, относящимися к конкретной архитектуре
* разделами, относящимися к конкретной операционной системе
* проблемами совместимости между различными версиями операционных систем
* существованием и определением макросов

=== Синтаксис условий RPM 

Если _expression_ истинно, то выполните какое-нибудь действие:

  %if expression
  ...
  %endif

Если _expression_ истинно, то выполните какое-нибудь действие, в другом случае выполните другое действие:

  %if expression
  ...
  %else
  ...
  %endif

// Если _expression_ не истинно, выполните какое-либо действие.

//  %if !expression
//   ...
//   %endif

// Если _expression_ не истинно, выполните какое-то действие, в противном случае выполните другое действие.

//  %if !expression
//  ...
//  %else
//  ...
//  %endif

=== Примеры условий RPM

==== Обозначение `%if` 

  %if 0%{?rhel} == 6
  sed -i '/AS_FUNCTION_DESCRIBE/ s/^/#/' configure.in
  sed -i '/AS_FUNCTION_DESCRIBE/ s/^/#/' acinclude.m4
  %endif

Это условие обрабатывает совместимость между  RHEL6 и другими операционными системами с точки зрения поддержки макроса AS_FUNCTION_DESCRIBE. Когда пакет создается для RHEL, определяется макрос `%rhel` , и он расширяется до версии RHEL. Если его значение равно 6, что означает, что пакет создан для RHEL 6, , то ссылки на
AS_FUNCTION_DESCRIBE, который не поддерживается RHEL6,  удаляются из сценариев автоконфигурации.

ifdef::community[]
  %if 0%{?el6}
  %global ruby_sitearch %(ruby -rrbconfig -e 'puts Config::CONFIG["sitearchdir"]')
  %endif

Это условие регулирует совместимость между Fedora версии 17 и новее и RHEL 6 с точки зрения поддержки макроса  `%ruby_sitearch` macro. Fedora версии 17 и никогда не определяет `%ruby_sitearch` по умолчанию, но RHEL6 не поддерживает этот макрос. Условие проверяет, является ли операционная система RHEL 6. Если это так,
`%ruby_sitearch` определяется явно. Обратите внимание, что  `0%{?el6}` имеет то же значение, что и `0%{?rhel} == 6` из предыдущего примера, и он проверяет, построен ли пакет на RHEL 6.
endif::community[]

ifdef::community[]
  %if 0%{?fedora} >= 19
  %global with_rubypick 1
  %endif

Это условие обрабатывает поддержку инструмента выбора ruby. Если операционная система Fedora версии 19 или новее, поддерживается rubypick.
endif::community[]

  %define ruby_archive %{name}-%{ruby_version}
  %if 0%{?milestone:1}%{?revision:1} != 0
  %define ruby_archive %{ruby_archive}-%{?milestone}%{?!milestone:%{?revision:r%{revision}}}
  %endif

Это условие обрабатывает определение макросов. Если заданы макросы `%milestone` или
`%revision`, переопределяется макрос `%ruby_archive`, который определяет имя вышестоящего файла архива.

==== Специальные варианты обозначения `%if`

Условные обозначения `%ifarch`, `%ifnarch` и `%ifos` являются специализированными вариантами условных обозначений `%if`. Эти варианты обычно используются, поэтому у них есть свои собственные макросы.

===== Обозначение`%ifarch` 

Условие `%ifarch` спользуется для начала блока SPEC файла, который зависит от архитектуры. За ним следует один или несколько спецификаторов архитектуры, каждый из которых разделен запятыми или пробелами.

  %ifarch i386 sparc
  ...
  %endif

Все содержимое SPEC файла между `%ifarch` и `%endif` обрабатывается только на 32-разрядных архитектурах AMD и Intel или системах на базе Sun SPARC.

===== Условное обозначение `%ifnarch`

Условие `%ifnarch` имеет обратную логику, чем условие  `%ifarch`.

  %ifnarch alpha
  ...
  %endif

Все содержимое SPEC файла между `%ifnarch` и `%endif` обрабатывается только в том случае, если оно не выполняется в системе на основе Digital Alpha/AXP.


===== Условие `%ifos` 

Условие `%ifos`  используется для управления обработкой на основе операционной системы сборки. За ним может следовать одно или несколько имен операционной системы.

  %ifos linux
  ...
  %endif

Все содержимое SPEC файла между `%ifos` и `%endif` обрабатывается только в том случае, если сборка была выполнена в системе Linux.
