[[welcome-apt]]
= Система управления пакетами. Знакомство с APT

Для установки, удаления и обновления программ и поддержания целостности системы в Linux в первую очередь стали использоваться _менеджеры пакетов_ (такие, как RPM в дистрибутивах `RedHat` или dpkg в `Debian GNU/Linux`). С точки зрения менеджера пакетов программное обеспечение представляет собой набор компонентов — программных _пакетов_. Такие компоненты содержат в себе набор исполняемых программ и вспомогательных файлов, необходимых для корректной работы ПО. Менеджеры пакетов дают возможность унифицировать и автоматизировать сборку бинарных пакетов и облегчают установку программ, позволяя проверять наличие необходимых для работы устанавливаемой программы компонент подходящей версии непосредственно в момент установки, а также производя все необходимые процедуры для регистрации программы во всех операционных средах пользователя. Сразу после установки программа оказывается доступна пользователю из командной строки и появляется в меню всех графических оболочек.

NOTE: Благодаря менеджерам пакетов, пользователю Linux обычно не требуется непосредственно обращаться к установочным процедурам отдельных программ или непосредственно работать с каталогами, в которых установлены исполняемые файлы и компоненты программ (обычно это `/usr/bin, /usr/share/имя_пакета`) — всю работу делает менеджер пакетов. Поэтому установку, обновление и удаление программ в Linux обычно называют управлением пакетами.

[[usage-apt]]
== Использование APT 

Система APT состоит из нескольких утилит. Главной и наиболее часто используемой является утилита управления пакетами *apt-get*: она автоматически определяет зависимости между пакетами и строго следит за их соблюдением при выполнении любой из следующих операций: установка, удаление или обновление пакетов.


NOTE: Использование утилит APT возможно только с правами root (режим суперпользователя)!


*apt-get* позволяет устанавливать в систему пакеты, требующие для своей работы другие, пока ещё не установленные. В этом случае он определяет, какие пакеты необходимо установить, и устанавливает их, пользуясь всеми доступными репозиториями. Для того, чтобы apt-get мог использовать тот или иной репозиторий, информацию о нем необходимо поместить в файл `/etc/apt/sources.list` и выполнить команду:

[source, bash]
----
# apt-get update

----

Эту команду необходимо также выполнять каждый раз, когда Вы собираетесь работать с репозиторием после длительного перерыва, так как при поиске пакетов APT должен руководствоваться базой данных, отражающей актуальное состояние репозитория. Такая база данных создаётся заново каждый раз, когда в репозитории происходит изменение: добавление, удаление или переименование пакета. Для ускорения работы *apt-get* хранит локальную копию базы данных, которая через некоторое время может уже не соответствовать реальному состоянию репозитория.

[[apt-installation]]
==  Установка и обновление пакета 

Установка пакета с помощью APT выполняется командой:

[source, bash]
----
# apt-get install имя_пакета

----

Команда *apt-get install __имя_пакета__* используется и для обновления уже установленного пакета или группы пакетов. В этом случае apt-get дополнительно проверяет, не обновилась ли версия пакета в репозитории по сравнению с установленным в системе.