[[welcome-apt]]
= Система управления пакетами. Знакомство с APT

Для установки, удаления и обновления программ и поддержания целостности системы в Linux в первую очередь стали использоваться _менеджеры пакетов_ (такие, как RPM в дистрибутивах `RedHat` или dpkg в `Debian GNU/Linux`). С точки зрения менеджера пакетов программное обеспечение представляет собой набор компонентов — программных _пакетов_. Такие компоненты содержат в себе набор исполняемых программ и вспомогательных файлов, необходимых для корректной работы ПО. Менеджеры пакетов дают возможность унифицировать и автоматизировать сборку бинарных пакетов и облегчают установку программ, позволяя проверять наличие необходимых для работы устанавливаемой программы компонент подходящей версии непосредственно в момент установки, а также производя все необходимые процедуры для регистрации программы во всех операционных средах пользователя. Сразу после установки программа оказывается доступна пользователю из командной строки и появляется в меню всех графических оболочек.

Полное описание APT можно узнать, перейдя по ссылке: https://docs.altlinux.org/ru-RU/archive/2.3/html-single/junior/alt-docs-junior/ch04s09.html[Установка и удаление программ (пакетов)]


NOTE: Установка пакетов в АЛЬТ Линукс осуществляется с помощью утилиты APT


NOTE: Для сокращения команд, встречающихся в тексте, будет использоваться нотация: 

* - команды без административных привелегий будут начинаться с символа "`$`"

* - команды с административными привелегиями будут начинаться с символа "`#`"

NOTE: По умолчанию `sudo` может быть отключено. Для получения административных привелегий используется команда `su`. Для включения `sudo` в стандартном режиме можно использовать команду:

[source, bash]
----
# control sudowheel enabled

----