[appendix]
= Новые возможности RPM в RHEL 7

Этот список документирует наиболее заметные изменения в упаковке RPM между Red Hat Enterprise Linux 6 и 7.

* Добавлена новая команда ``rpmkeys``, используемая для импорта связки ключей и проверки подписи.

* Добавлена новая команда ``rpmspec``, используемая для запросов спецификаций и анализируемых выходных данных.

* Добавлена новая команда ``rpmsign``,  используемая для подписи пакета.
* Расширения  ``posix.exec()``  и ``os.exit()`` встроенные в  ``%{lua:...}``
скрипты, завершают работу скрипта с ошибкой, если они не вызываются из дочернего процесса, созданного с помощью скриптлета
``posix.fork()``.
* Сбой скриптлета ``%pretrans``  приводит к пропуску установки пакета
* Скриптлеты могут быть развернуты макросом и развернуты в формате запроса во время выполнения
* Зависимости скриптлетов до транзакции и после транзакции теперь могут быть правильно выражены с помощью  ``Requires(pretrans)`` , ``Requires(posttrans)`` и
скриптлетов.
* Добавлен тег ``OrderWithRequires``  для предоставления дополнительных подсказок. Тег следует синтаксису тега  ``Requires``, но не создает фактических зависимостей. Подсказки по порядку обрабатываются так, как если бы они были ``Requires`` при расчете порядка транзакции, только если задействованные пакеты присутствуют в одной и той же транзакции.
* The ``%license``. Этот флаг можно использовать в разделе ``%files`. Можно использовать аналогично флагу ``%doc`` для пометки файлов как лицензий, которые необходимо установить, несмотря на параметр ``--nodocs``.
* Добавлен макрос ``%autosetup`` для автоматизации применения исправлений с дополнительной интеграцией с распределенной системой контроля версий.
* Автоматический генератор зависимостей был переписан в расширяемую и настраиваемую систему на основе правил со встроенной фильтрацией.
* Открытые ключи OpenPGP V3 больше не поддерживаются.
