[[hello-gear]]
= Инструмент Gear

== Вступление

Gear (Get Every Archive from git package Repository) - система для работы с произвольными архивами программ. В качестве хранилища данных gear использует ``git``, что позволяет работать с полной историей проекта.

Основной смысл хранения исходного кода пакетов в `git-репозитории` заключается в более эффективной и удобной совместной разработке, а также в минимизации используемого дискового пространства для хранения архива репозитория за длительный срок и минимизации трафика при обновлении исходного кода.

Идея gear заключается в том, чтобы с помощью одного файла с простыми правилами (для обработки которых достаточно sed и git) можно было бы собирать пакеты из произвольно устроенного git-репозитория, по аналогии с hasher, который был задуман как средство для сборки пакетов из произвольных 'srpm-пакетов'.

=== Структура репозитория

Хотя `gear` и не накладывает ограничений на внутреннюю организацию git-репозитория (не считая требования наличия файла с правилами), есть несколько соображений о том, как более эффективно и удобно организовывать git-репозитории, предназначенные для хранения исходного кода пакетов.

Одна сущность — один репозиторий::

Не стоит помещать в один репозиторий несколько разных пакетов, за исключением случаев, когда у этих пакетов есть общий пакет-предок.

*  Плюсы: Соблюдение этого правила облегчает совместную работу над пакетом, поскольку неперегруженный репозиторий легче клонировать и в целом инструментарий git больше подходит для работы с такими репозиториями.

*  Минусы: Несколько сложнее выполнять операции *fetch* и *push* в случае, когда репозиториев, которые надо обработать, много. Впрочем, *fetch/push* в цикле выручает.

Несжатый исходный код::

Сжатый разными средствами (`gzip`, `bzip2` и т.п.) исходный код лучше хранить в git-репозитории в несжатом виде.

* Плюсы: Изменение файлов, которые помещены в репозиторий в сжатом виде, менее удобно отслеживать штатными средствами (*git diff*). Поскольку git хранит объекты в сжатом виде, двойное сжатие редко приводит к экономии дискового пространства. Наконец, алгоритм, применяемый для минимизации трафика при обновлении репозитория по протоколу git, более эффективен на несжатых данных.

* Минусы: Поскольку некоторые виды сжатия одних и тех же данных могут приводить к разным результатам, может уменьшиться степень первозданности (нативности) исходного кода.

Распакованный исходный код::

Исходный код, запакованный архиваторами (`tar`, `cpio`, `zip` и т.п.), лучше хранить в ``git``-репозитории в распакованном виде.

* Плюсы: Существенно удобнее вносить изменения в конечные файлы и отслеживать изменения в них, заметно меньше трафик при обновлении.

* Минусы: Поскольку ``git`` из информации о владельце, правах доступа и дате модификации файлов хранит только исполняемость файлов, любой архив, созданный из репозитория, будет по этим параметрам отличаться от первозданного. Помимо потери нативности, изменение прав доступа и даты модификации может теоретически повлиять на результат сборки пакета. Впрочем, сборку таких пакетов, если они будут обнаружены, всё равно придётся исправить.

Форматированный changelog::

В changelog релизного ``commit'а`` имеет смысл включать соответствующий текст из ``changelog'а`` пакета, как это делают утилиты ``gear-commit`` (обёртка к ``git commit``, специально предназначенная для этих целей) и ``gear-srpmimport``. В результате можно будет получить представление об изменениях в очередном релизе пакета, не заглядывая в spec-файл самого пакета.

=== Правила экспорта

С одной стороны, для того, чтобы srpm-пакет мог быть импортирован в git-репозиторий наиболее удобным для пользователя способом, язык правил, согласно которым производится экспорт из коммита репозитория (в форму, из которой можно однозначно изготовить srpm-пакет или запустить сборку), должен быть достаточно выразительным.

С другой стороны, для того, чтобы можно было относительно безбоязненно собирать пакеты из чужих gear-репозиториев, этот язык правил должен быть достаточно простым.

Файл правил экспорта (по умолчанию в ``.gear/rules``) состоит из строк формата:

[source,txt]

----

директива: параметры

----

Параметры разделяются пробельными символами.

Директивы позволяют экспортировать:

. Любой файл из дерева, соответствующего коммиту; 

. Любой каталог из дерева, соответствующего коммиту в виде ``tar-`` или ``zip-архива``; 

. ``nified diff`` между любыми каталогами, соответствующими коммитам.

Файлы на выходе могут быть сжаты разными средствами (`gzip`, `bzip2` и т.п.). В качестве коммита может быть указан как целевой коммит (значение параметра -t утилиты gear), так и любой из его предков при соблюдении условий, гарантирующих однозначное вычисление полного имени коммита-предка по целевому коммиту.

(Правила экспорта из gear-репозитория описаны детально в ``gear-rules``.)(ссылка под редактуру)


=== Основные типы устройства gear-репозитория

Правила экспорта реализуют основные типы устройства gear-репозитория следующим образом:

Архив с модифицированным исходным кодом::

С помощью простого правила

[source,bash]

----

tar: .

----

Всё дерево исходного кода экспортируется в один tar-архив. Если у проекта есть upstream, публикующий tar-архивы, то добавление релиза в имя tar-архива, например, с помощью правила:

[source,bash]

----

tar: . name=@name@-@version@-@release@

----

позволяет избежать коллизий.

Архив с немодифицированным исходным кодом и патчем, содержащем локальные изменения::

Если дерево с немодифицированным исходным кодом хранится в отдельном подкаталоге, а локальные изменения хранятся в gear-репозитории в виде отдельных патч-файлов, то правила экспорта могут выглядеть следующим образом:

[source,bash]

----
tar: package_name
copy: *.patch

----

Такое устройство репозитория получается при использовании утилиты ``gear-srpmimport``, предназначенной для быстрой миграции от srpm-файла к ``gear``-репозиторию.

Смешанные типы::

Вышеперечисленные типы устройства gear-репозитория являются основными, но не исчерпывающими. Правила экспорта достаточно выразительны для того, чтобы реализовать всевозможные сочетания основных типов и создать полнофункциональный gear-репозиторий на любой вкус.


[[quick-start-gear]]
== Быстрый старт Gear

=== Создание gear-репозитория путём импорта созданного ранее srpm-пакета.

Пусть у нас есть srpm-пакет ``foobar-1.0-alt1.src.rpm``, и, к примеру, в нём находится следующее:

[source,bash]

----
$ rpm -qpl foobar-1.0-alt1.src.rpm
foobar-1-fix.patch
foobar-2-fix.patch
foobar.icon.png
foobar-1.0.tar.bz2
foobar-plugins.tar.gz
----

Для того чтобы сделать из него gear-репозиторий, нам нужно:

. Создать каталог, в котором будет располагаться наш архив: 
+
[source,bash]

----
$ mkdir foobar
$ cd foobar
----

. Создать новый git-репозиторий: 
+
[source,bash]

----
$ git init
Initialized empty Git repository in .git/
----
+
Получившийся пустой git-репозиторий будет выглядеть примерно следующим образом:
+
[source,bash]

----
$ ls -dlog .*
drwxr-xr-x 4 4096 Aug 12 34:56 .
drwxr-xr-x 6 4096 Aug 12 34:56 ..
drwxr-xr-x 8 4096 Aug 12 34:56 .git
----
+
Таким образом, git-репозиторий готов для импорта srpm-пакета.   
+
. В проекте ``gear`` есть утилита gear-srpmimport, предназначенная для автоматизации импортирования srpm-пакета в git-репозиторий: 
+
[source,bash]

----
$ gear-srpmimport foobar-1.0-alt1.src.rpm
Committing initial tree deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
gear-srpmimport: Imported foobar-1.0-alt1.src.rpm
gear-srpmimport: Created master branch
----
+
После выполнения импорта git-репозиторий будет выглядеть следующим образом:
+
[source,bash]

----
$ ls -Alog
drwxr-xr-x 1 4096 Aug 12 34:56 .gear
drwxr-xr-x 1 4096 Aug 12 34:56 .git
-rw-r--r-- 1 6637 Aug 12 34:56 foobar.spec
drwxr-xr-x 3 4096 Aug 12 34:56 foobar
drwxr-xr-x 3 4096 Aug 12 34:56 foobar-plugins
-rw-r--r-- 1  791 Aug 12 34:56 foobar-1-fix.patch
-rw-r--r-- 1 3115 Aug 12 34:56 foobar-2-fix.patch
-rw-r--r-- 1  842 Aug 12 34:56 foobar.icon.png
----
+
. При необходимости в файл правил можно вносить изменения. Например, можно убрать сжатие исходников (соответствующие изменения следует вносить и в spec-файл). 


=== Создание gear-репозитория на основе готового git-репозитория

. Создать и добавить в git-репозиторий spec-файл.

. Создать и добавить в git-репозиторий файл с правилами .gear/rules.

=== Сборка пакета из gear-репозитория

. Сборка пакета при помощи hasher осуществляется командой gear-hsh:
+
[source,bash]
----
$ gear-hsh   
----

.  Чтобы собрать старый пакет, который не содержит определения тега Packager в spec-файле, следует отключить соответствующую проверку: 

+
[source,bash]
----
$ gear-hsh --no-sisyphus-check=gpg,packager 
----

. Сборка пакета при помощи rpmbuild(8) осуществляется командой gear-rpm: 
+
[source,bash]
----
$ gear-rpm -ba 
----




=== Фиксация изменений в репозитории

. Для того, чтобы сделать commit очередной сборки пакета, имеет смысл воспользоваться утилитой ``gear-commit``, которая помогает сформировать список изменений на основе записи в spec-файле:
+
[source,bash]
----
$ gear-commit -a
----  
+
. Прежде чем сделать первый commit, не забудьте сконфигурировать ваш адрес. Это можно сделать глобально несколькими способами, например, прописав соответствующие значения в 
``~/.gitconfig``: 
+
[source,bash]
----
$ git config --global user.name 'Your Name'
$ git config --global user.email '<login>@altlinux.org'
----  
+
Для отдельно взятого git-репозитория сконфигурировать адрес можно, прописав соответствующие значения в ``.git/config`` этого git-репозитория:
+
[source,bash]
----
$ git config user.name 'Your Name'
$ git config user.email '<login>@altlinux.org'
----