= Hasher start 

== Что такое hasher?

*Hasher* — это инструмент безопасной и воспроизводимой сборки пакетов. Все пакеты репозитория https://www.altlinux.org/Sisyphus[`*_Сизиф_*`] собираются с его помощью.


== Принцип действия

*`Hasher`* — инструмент для сборки пакетов в «чистой» и контролируемой среде. Это достигается с помощью создания в chroot минимальной сборочной среды, установки туда указанных в source-пакете сборочных зависимостей и сборке пакета в свежесозданной среде. Для сборки каждого пакета сборочная среда создаётся заново.

Такой принцип сборки имеет несколько следствий:

. Все необходимые для сборки зависимости должны быть указаны в пакете. Для облегчения поддержки сборочных зависимостей в актуальном состоянии в https://www.altlinux.org/Sisyphus[`*_Сизифе_*`] придуман инструмент под названием buildreq,

. Сборка не зависит от конфигурации компьютера пользователя, собирающего пакет, и может быть повторена на другом компьютере,

. Изолированность среды сборки позволяет с лёгкостью собирать на одном компьютере пакеты для разных дистрибутивов и веток репозитория — для этого достаточно лишь направить hasher на различные репозитории для каждого сборочного окружения.





== Настройка Hasher 

Установка Hasher: 

[source,bash]

----

# apt-get install hasher

----

Добавление пользователя:

Hasher использует специальных вспомогательных пользователей и группу `hashman` для своей работы, поэтому каждого пользователя, желающего использовать `hasher`, перед началом работы нужно зарегистрировать:

[source,bash]

----
# hasher-useradd USER

----

Настройка сборочной среды:

Для работы `hasher` требуется создать директорию, в которой будет строиться сборочная среда:

[source,bash]

----

$ mkdir ~/.hasher

----

Рабочий каталог (в данном случае ~/.hasher) должен быть доступен на запись пользователю, запускающему сборку.

Кроме того, его нельзя располагать на файловой системе, которая смонтирована с опциями `noexec` или `nodev` — в таких условиях `hasher` не сможет создать корректное сборочное окружение.

Сборочное окружение можно создать явно:



[source,bash]

----

$ hsh --initroot-only ~/.hasher

----

Явное создание необязательно — при необходимости оно будет произведено при первой сборке пакета.

Hasher берёт пакеты для установки из APT-источников. По умолчанию в сборочную среду копируется список источников, указанный в конфигурации APT хост-системы; также можно явно задать дополнительные репозитории, указав альтернативный файл конфигурации APT:

[source,bash]

----

$ hsh --apt-config=branch4.1-apt.conf --initroot-only ~/.hasher

----

В таком файле конфигурации необходимо указать расположение файла с APT-источниками:

[source,bash]

----

$ hsh --apt-config=branch4.1-apt.conf --initroot-only ~/.hasher

----



== Сборка в hasher

Сборка происходит от обычного пользователя, добавленного с помощью hasher-useradd:


[source, bash]
----

hsh ~/.hasher /home/work/rpm/package.src.rpm

----


При удачной сборке полученные пакеты будут лежать в `*~/.hasher/repo/<платформа>/RPMS.hasher/*`, в противном случае на stdout будет выведена информация об ошибках сборки.

Создаваемый hasher репозиторий является обычным APT-репозиторием и может быть использован в sources.list[3]. Также он будет использован при дальнейшей сборке пакетов (это поведение можно регулировать ключом --without-stuff).

Если вы держите сборочную среду в tmpfs (см. ниже), каталог ~/.hasher/repo, вероятно, не переживёт перезагрузку системы. Репозиторий можно переместить в постоянное место, указав в настроечном файле hasher .hasher/config параметр def_repo=постоянное_хранилище (или вызвав hasher с ключом --repo).


== Сборочные зависимости

Сборочные зависимости RPM делятся на два вида:

. необходимые для корректного создания src.rpm из spec-файла (содержащие определения RPM-макросов, используемых в spec-файле),
  
. все остальные (необходимые для непосредственной сборки).

Поскольку `hasher` собирает пакеты из src.rpm (не считая поддержки `gear`), то для сборки необходимо иметь в хост-системе установленные   сборочные зависимости первого типа. Большинство таких зависимостей (но пока не все) содержатся в пакетах с названием `rpm-build-*`.

Поскольку сборка src.rpm либо завершается неудачно (при отсутствии сборочной зависимости первого типа), либо корректно, то собирать src.rpm-пакеты в хост системе можно с помощью `*--nodeps*`:

[source, bash]
----
rpm -bs --nodeps package.spec
----

Сам `hasher`, в отличие от `gear`, не предъявляет никаких требований к разделению сборочных зависимостей на первый и второй тип. Однако для совместимости с `gear` и для улучшения описания spec-файла рекомендуется распределять их так:

* В поле BuildRequires(pre) помещать сборочные зависимости, требуемые для сборки src.rpm,
* В поле BuildRequires — все остальные.


NOTE: в поле BuildRequires(pre) нельзя использовать макросы.


== man hasher

Для получение подробной справки и пояснении команд - воспользуйтесь мануалом `hasher`:

[source, bash]

----
$ man hsh
----


== Монтирование файловых систем внутри hasher

Некоторым приложениям для сборки требуется смонтированная файловая система (например, /proc). hasher поддерживает монтирование дополнительных файловых систем в сборочную среду.

Монтирование происходит при одновременном выполнении следующих четырех условий:

* файловая система описана в файле `*/etc/hasher-priv/fstab*`, либо является одной из предопределённых: `*/proc*`, ~*/dev/pts*~, `*/sys*`;
в конфигурации hasher-priv `*(/etc/hasher-priv/system)*` ФС указана в опции `allowed_mountpoints`;

* файловая система указана в опции `--mountpoints` при запуске `hasher`, либо, аналогично, в ключе `known_mountpoints` конфигурационного файла hasher `*(~/.hasher/config)*`;

* файловая система указана сборочной зависимостью `*(например, BuildReq: /proc)*` собираемого пакета, прямой или косвенной (через зависимости сборочных зависимостей пакета).



