[[introduction]]
= Вступление

Уважаемый читатель! Данное руководство нацелено на подробное изучение сборки пакетов "с нуля". Для того, чтобы следовать ему, убедительная просьба внимательно читать текст, переходить по ссылкам, которые представлены в тексте. В них может быть предоставлена дополнительная информация, раскрывающая те темы, которые кратко описаны в данной документации. 



ifdef::community[]
[[pdf-version]]
== PDF Версия

Вы также можете скачать
https://alt-packaging-guide.github.io/alt-packaging-guide.pdf[PDF версию
данного документа].
endif::community[]

[[document-conventions]]
== Структура документации

Перед тем, как приступить к сборке, нужно создать структуру каталогов, необходимую RPM, находящуюся в Вашем «домашнем» каталоге:

* Отображение файловой структуры будет представлено следующим образом:

+

[source,bash]
----
$ tree ~/RPM/
/home/user/RPM/
|-- BUILD
|-- BUILDROOT
|-- RPMS
|   |-- i586
|   |-- x86_64
|   `-- noarch
|-- SOURCES
|-- SPECS
`-- SRPMS

----

* В дальнейшем вывод команд будет продемонстрирован следующим образом:



+

[source,txt]
----
Name:           bello
Version:
Release:        alt1
Summary:

----


* Темы, представляющие интерес, или словарные термины упоминаются либо как ссылки на соответствующую документацию или веб-сайт выделены **жирным** шрифтом, либо __курсивом__. Первые упоминания некоторых терминов ссылаются на соответствующую документацию.

* Названия утилит, команд и других элементов, обычно встречающихся в коде, написаны ``моноширинным`` шрифтом.

