[[introduction]]
= Вступление

Уважаемый читатель! 

Мы хотим обратить Ваше внимание на то, что для успешного прохождения руководства необходимо внимательно читать текст и уделять внимание деталям. Каждый раздел содержит информацию, которая поможет Вам понять процесс сборки пакетов и улучшить свои навыки в этой области. 

В тексте документации присутствуют ссылки на дополнительную информацию. Мы настоятельно рекомендуем Вам переходить по этим ссылкам и ознакомляться с материалами более подробно. Это поможет Вам лучше понимать темы, раскрытые в руководстве, и получить полезную дополнительную информацию. 


[[pdf-version]]
== PDF Версия

Вы также можете скачать
https://alt-packaging-guide.github.io/alt-packaging-guide.pdf[PDF версию
данного документа].


[[document-conventions]]
== Структура документации

Перед тем, как приступить к сборке, нужно создать структуру каталогов, необходимую RPM, находящуюся в Вашем «домашнем» каталоге:

* Отображение файловой структуры будет представлено следующим образом:

+

[source,bash]
----
$ tree ~/RPM/
/home/user/RPM/
|-- BUILD
|-- BUILDROOT
|-- RPMS
|   |-- i586
|   |-- x86_64
|   `-- noarch
|-- SOURCES
|-- SPECS
`-- SRPMS

----

* В дальнейшем вывод команд будет продемонстрирован следующим образом:



+

[source,txt]
----
Name:           bello
Version:
Release:        alt1
Summary:

----


* Темы, представляющие интерес, или словарные термины упоминаются либо как ссылки на соответствующую документацию или веб-сайт выделены **жирным** шрифтом, либо __курсивом__. Первые упоминания некоторых терминов ссылаются на соответствующую документацию.

* Названия утилит, команд и других элементов, обычно встречающихся в коде, написаны ``моноширинным`` шрифтом.


NOTE: Для сокращения команд, встречающихся в тексте, будет использоваться нотация: 

* - команды без административных привилегий будут начинаться с символа "`$`"

* - команды с административными привилегиями будут начинаться с символа "`#`"

NOTE: По умолчанию `sudo` может быть отключено. Для получения административных привилегий используется команда `su`. Для включения `sudo` в стандартном режиме можно использовать команду:

[source, bash]
----
# control sudowheel enabled

----


== Вклад в руководство

Вы можете внести свой вклад в это руководство, отправив запрос на принятие изменений  (Pull Request) в  
https://github.com/altlinux/alt-packaging-guide[репозиторий].



[[prerequisites]]
== Установка необходимых пакетов для процесса сборки

Чтобы следовать данному руководству, Вам потребуется установить следующие пакеты: 

NOTE: Некоторые из этих пакетов устанавливаются по умолчанию в
https://www.altlinux.org/Releases[Альт]. Установка проводится с правами суперпользователя.



[source,bash]
----
# apt-get update 

Получено: 1 http://ftp.altlinux.org p10/branch/x86_64 release [4223B]
Получено: 2 http://ftp.altlinux.org p10/branch/x86_64-i586 release [1665B]
Получено: 3 http://ftp.altlinux.org p10/branch/noarch release [2844B]
Получено 8732B за 0s (81,8kB/s).                    
Найдено http://ftp.altlinux.org p10/branch/x86_64/classic pkglist
Найдено http://ftp.altlinux.org p10/branch/x86_64/classic release
Найдено http://ftp.altlinux.org p10/branch/x86_64/gostcrypto pkglist
Найдено http://ftp.altlinux.org p10/branch/x86_64/gostcrypto release
Найдено http://ftp.altlinux.org p10/branch/x86_64-i586/classic pkglist
Найдено http://ftp.altlinux.org p10/branch/x86_64-i586/classic release
Найдено http://ftp.altlinux.org p10/branch/noarch/classic pkglist
Найдено http://ftp.altlinux.org p10/branch/noarch/classic release
Чтение списков пакетов... Завершено
Построение дерева зависимостей... Завершено

# apt-get install gcc rpm-build rpmlint make python gear hasher patch rpmdevtools 
----

