[[introduction]]
== Вступление

Руководство по сборке RPM пакетов:

Как подготовить исходный код для сборки RPM.:: Ссылка на раздел для тех, кто не имеет опыта разработки ПО.
xref:preparing-software-for-packaging[].

Как собрать исходный код в RPM.:: 
Ссылка на раздел для разработчиков ПО, которым необходимо собрать программное обеспечение в RPM пакеты. xref:packaging-software[].

Расширенные сценарии сборки.::
 Эта ссылка на справочный материал для сборщиков RPM, работающих с расширенными сценариями сборки RPM.                
 xref:advanced-topics[].

ifdef::community[]
[[pdf-version]]
== PDF Версия

Вы также можете скачать
https://alt-packaging-guide.github.io/alt-packaging-guide.pdf[PDF версию
данного документа].
endif::community[]

[[document-conventions]]
== Структура документации

Перед тем, как приступить к сборке, нужно создать структуру каталогов, необходимую RPM, находящуюся в Вашем «домашнем» каталоге:

* Отображение файловой структуры будет представлено следующим образом:

+

[source,bash]
----
$ tree ~/RPM/
/home/user/RPM/
|-- BUILD
|-- BUILDROOT
|-- RPMS
|   |-- i586
|   |-- x86_64
|   `-- noarch
|-- SOURCES
|-- SPECS
`-- SRPMS

----

* В дальнейшем вывод команд будет продемонстрирован следующим образом:



+

[source,txt]
----
Name:           bello
Version:
Release:        alt1
Summary:

----


* Темы, представляющие интерес, или словарные термины упоминаются либо как ссылки на соответствующую документацию или веб-сайт выделены **жирным** шрифтом, либо __курсивом__. Первые упоминания некоторых терминов ссылаются на соответствующую документацию.

* Названия утилит, команд и других элементов, обычно встречающихся в коде, написаны ``моноширинным`` шрифтом.

== Вклад в руководство

