[[Join]]

= Join 

Если Вы считаете, что какого-то пакета в Сизифе не хватает, или какой-то пакет заслуживает большего внимания и готовы заняться им — значит, настало время присоединиться к команде
 https://www.altlinux.org/ALT_Linux_Team[ALT Linux Team].

Процедура Join - это процесс вступления в ALT Linux Team, результатом которого является возможность непосредственно участвовать в разработке репозитория Сизиф. После прохождения Join Вы станете мейнтенером. 

Кто такой мейнтейнер?  У каждого пакета в репозитории Сизиф есть один или несколько мейнтейнеров — это те участники ALT Linux Team, которые собирают новые версии пакета, следят за ошибками, которые заводят пользователи в багтрекере и общаются с upstream-разработчиками программы. 

== Процедура принятия в Team

Для принятия человека в Team создаётся небольшая команда заинтересованных в этом тимовцев:

. Секретарь команды. В его обязанность входит отслеживать стадии принятия и выполнять административные действия.

. Ментор вступающего. Он помогает кандидату со вступлением, отвечает на его вопросы и принимает решение о готовности кандидата

. Рецензент работы вступающего. Он проводит независимую оценку готовности вступающего по результатам его работы и подтверждает его готовность.

. Сам кандидат.

== Сбор информации

Для принятия в https://www.altlinux.org/ALT_Linux_Team[ALT Linux Team] необходима следующая информация:

. Имя ментора — участника команды, имеющего желание помогать в процессе приёма в Team. Менторов можно искать в https://www.altlinux.org/Списки_рассылки[списках рассылки], канале https://telegram.me/alt_linux[Telegram], или узнать у Ваших знакомых членов сообщества ALT Linux Team, если таковые есть, готовы ли они стать Вашим ментором.

. Псевдоним участника (имя пользователя). Выбирается им самим. Имя должно начинаться с буквы, содержать только строчные латинские буквы и цифры, быть не короче трёх символов. 

NOTE: Псевдоним — это фактичеcки Ваше второе имя в команде. Так Вас будут называть в глаза и за глаза, по нему на Вас будут ссылаться. Поэтому псевдоним лучше выбирать короткий, запоминающийся и не отягощённый мусором. Например, `yoda` — удобный псевдоним, а `travellingwilburys1998` — неудобный. Список уже занятых имён можно посмотреть в пакете https://git.altlinux.org/gears/a/alt-gpgkeys.git?p=alt-gpgkeys.git;a=tree;f=keys[alt-gpgkeys].

. адрес почты, на который будет производиться пересылка с адреса _псевдоним@altlinux.org_;

. SSH-ключ (ED25519 или RSA >= 4096bit). Принимающему нужна публичная часть ключа. Этот ключ будет использоваться для SSH-доступа на ресурсы Sisyphus (https://www.altlinux.org/Git.alt[git.alt] и другие);

. GPG-ключ (RSA >= 4096bit). В ключе должны быть имя в формате "<First name> <Last name>" и uid вида _псевдоним@altlinux.org_. Принимающему нужна публичная часть ключа. Этот ключ будет использоваться для подписи пакетов и для удостоверения личности в почте.


Если у вас ещё нет SSH- или GPG-ключа, прочтите статью https://www.altlinux.org/Работа_с_ключами_разработчика[Работа с ключами разработчика].


== Создание заявки

Когда Вы нашли своего куратора процедуры join - ментора, Вам необходимо зафиксировать начало вашей работы. На этом этапе вам понадобятся два ресурса: https://bugzilla.altlinux.org[BugZilla]. В данном случае bugzilla выступает площадкой для процедуры вступления в ALT Linux Team. Здесь ведётся официальный диалог с участниками, Вы можете посмотреть прогресс других кандидатов, узнать, какие задачи они взяли. Введите в поиске `join` и увидите список, относящийся к этой тематике.

Для начала необходимо пройти регистрацию на Багзилле https://bugzilla.altlinux.org[BugZilla].

После того, как Вы прошли регистрацию и нашли ментора, можно начинать регистрировать заявку. Регистрация заявки происходит следующим образом: на главной странице сайта ALT Bugzilla выберите `"Зарегистрировать ошибку"` или `"Новая ошибка"`. Будущие участники ALT Linux Team регистрируются в разделе 
`Team Accounts: ALT Linux Team: присоединение`. 
При наведении мыши будут видны подсказки к заполнению полей формы. Клик по любому из пунктов формы приведёт вас на страницу https://bugzilla.altlinux.org/page.cgi?id=fields.html#short_desc[Поля ошибок] с описанием терминов. Выберите компонент _Join_. Если Вы посмотрите другие компоненты, то убедитесь, что они не так популярны. При выборе уровня важности задачи учитывайте, что мейнтенеры просматривают ошибки в том числе по этому фильтру. Также будет видно, к какому разделу относится ваша задача. (Важность определяете Вы сами, исходя из своих возможностей и целеполагания. Скорее, это параметр для вас.) Поставим здесь средний приоритет `Р3`. Платформа определяется автоматически. Здесь же Вы можете изменить значения, в том числе поставить all, и научиться собирать пакеты для любых платформ.

Отметим новое состояние нашей заявки.

Поля _Исполнитель_ и _Приёмка_ заполнятся автоматически. В пункте _Подписчики_ укажем всех, кто заинтересован в решении этой задачи. В случае join - это ментор.

В стандартной форме bugzilla есть поле для заполнения адреса URL, с которым может быть связана ошибка. Так как мы регистрируем по сути наше участие в прохождении Join, отметьте страницу на вики https://www.altlinux.org/Team/Join[Join]

Поле Аннотация предназначено для краткого описания сути ошибки. Так как мы заводим эту ошибку в рамках вступления в ALT Linux Team, напишем join с указанием предполагаемой почты: `join user@`. 

Пример комментария к открытой заявке на вступление в ALT Linux Team.

-------

Псевдоним: sova
Почта: Valentin Sokolov <sova@altlinux.org>
Адрес пересылки почты: sokolovvaly.158@gmail.com
Имя ментора: Grigory Ustinov
Почта ментора: grenka@altlinux.org

Хочу научиться собирать пакеты.

-------


На данном этапе прикреплять SSH-ключ и GPG-ключ необязательно. Остальные поля не заполняем.

Мы создали заявку на вступление в ALT Linux Team. Её закрытие будет означать либо успешное прохождение процедуры и получение доступов к работе с Сизифом и вступление в Team, либо отказ в нём.




