[[Join]]

= Join 

Процедура Join - это процесс вступления в ALT Linux Team, результатом которого является возможность непосредственно участвовать в разработке репозитория Сизиф. После прохождения Join вы станете мейнтенером. 

Кто такой мейнтейнер?  У каждого пакета в репозитории Сизиф есть один или несколько мейнтейнеров — это те участники ALT Linux Team, которые собирают новые версии пакета, следят за ошибками, которые заводят пользователи в багтрекере и общаются с upstream-разработчиками программы. 

== Этапы процедуры принятия в Team

== Создание заявки

Необходимым этапом в создании заявки является поиск своего ментора. Когда вы нашли своего куратора процедуры join - то есть ментора, вам необходимо зафиксировать начало вашей работы. На этом этапе вам понадобятся два ресурса: https://bugzilla.altlinux.org. В данном случае bugzilla выступает площадкой для процедуры вступления в ALT Linux Team. Здесь ведётся официальный диалог с участниками, вы можете посмотреть прогресс других кандидатов, какие задачи они взяли. Введите в поиске join и увидите список, относящийся к этой тематике.

Для начала необходимо пройти регистрацию на Багзилле <https://bugzilla.altlinux.org>.

После того, как Вы прошли регистрацию и нашли ментора, можно начинать регестрировать заявку. Регистрация заявки происходит следующим образом: на главной странице сайта ALT Bugzilla выберете "Зарегистрировать ошибку" или "Новая ошибка". Будущие участники ALT Linux Team регистрируются в разделе 
Team Accounts: ALT Linux Team: присоединение. 
При наведении мыши будут видны подсказки к заполнению полей формы. Клик по любому из пунктов формы приведёт вас на страницу <https://bugzilla.altlinux.org/page.cgi?id=fields.html#short_desc> с описанием терминов. Выберете компонент Join. Если Вы посмотрите другие компоненты, то убедитесь, что они не так популярны. При выборе уровня важности задачи учитывайте, что мейнтенеры просматривают ошибки в том числе по этому фильтру. Также будет видно, к какому разделу относится ваша задача. (Важность определяете вы сами, исходя из своих возможностей и целеполагания. Скорее, это параметр для вас.) Поставим здесь средний приоритет Р3. Платформа вашего рабочего места определяется автоматически. Здесь же вы можете изменить значения, в том числе поставить all. И научиться собирать пакеты для любых платформ.

Отметим новое состояние нашей заявки.

Поля Исполнитель и Приёмка заполнятся автоматически. В пункте Подписчики укажем всех, кто заинтересован в решении этой задачи. В случае join - это ментор.

В стандартной форме bugzilla есть поле для заполнения адреса URL, с которым может быть связана ошибка. Так как мы регистрируем по сути наше участие в прохождении Join, отметьте страницу на вики <https://www.altlinux.org/Team/Join>

Поле Аннотация предназначено для краткого описания сути ошибки. Так как мы заводим эту ошибку в рамках вступления в ALT Linux Team, напишем join с указанием предполагаемой почты: join user@. Проверить, не занят ли ваш ник, можно на странице: http://sisyphus.ru/ru/people/.

Пример комментария к открытой заявке на вступление в ALT Linux Team.

-------

Псевдоним: sova
Почта: Valentin Sokolov <sova@altlinux.org>
Адрес пересылки почты: sokolovvaly.158@gmail.com
Имя ментора: Grigory Ustinov
Почта ментора: grenka@altlinux.org

Хочу научиться собирать пакеты.

-------


На данном этапе прикреплять SSH-ключ и GPG-ключ необязательно. Остальные поля не заполняем.

Мы создали заявку на вступление в ALT Linux Team. Её закрытие будет означать либо успешное прохождение процедуры и получение доступов к работе с Сизифом и вступление в Team, либо отказ в нём.




