[[rpm-macros]]
=== RPM Макросы

https://rpm-software-management.github.io/rpm/manual/macros.html[Макрос RPM] - это прямая замена текста, которая может быть условно назначена на основе необязательной оценки оператора при использовании определенной встроенной функциональности. Это означает, что Вы можете заставить RPM выполнять замены текста за Вас.

Это полезно, например, при многократной ссылке на __Version__ упакованного программного обеспечения в файле спецификации. Вы определяете __Version__ только один раз - в макросе ``%{version}``. Затем используйте ``%{version}`` во всем файле спецификации. Каждый раз, во время определения строки ``%{version}``, в конечном итоге будет подставлена __Version__ программы, которую вы определили ранее.

[NOTE]
====
Если Вы видите незнакомый макрос, Вы можете узнать о нём с помощью:

[source,bash]
----
$ rpm --eval %{_MACRO}

----

Например:

[source,bash]
----
$ rpm --eval %{_bindir}
/usr/bin

$ rpm --eval %{_libexecdir}
/usr/libexec

----

====

Распространённым макросом является ``%{?dist}``, который обозначает “тег распространения”. Он сигнализирует, какой дистрибутив используется для сборки.

Например:

ifdef::community[]
[source,bash]
----
# On a RHEL 7.x machine
$ rpm --eval %{?dist}
.el7

# On a Fedora 23 machine
$ rpm --eval %{?dist}
.fc23

----
endif::community[]

ifdef::rhel[]
[source,bash]
----
# On a RHEL 7.x machine
$ rpm --eval %{?dist}
.el7

----
endif::rhel[]

Больше информации о макросах см. в разделе xref:more-on-macros[Подробнее о макросах].