
[[what-is-an-rpm]]
= Что такое RPM-пакет?

RPM-пакет - это архив, содержащий в себе архив https://en.wikipedia.org/wiki/Cpio[.cpio] с файлами, а также метаданные - имя пакета, его описание, зависимости и т.д. 

Существует два типа RPM-пакетов:

* SRPM-пакеты (исходники) - архив с расширением `.src.rpm` 
* RPM-пакеты - архив с расширением `.rpm`.

SRPM и RPM-пакеты имеют общий формат, но имеют разное содержимое и служат разным целям. SRPM содержит исходный код, при необходимости патчи к нему и spec-файл, в котором описывается, как собрать исходный код в RPM-пакет.

RPM-пакет содержит исполняемые файлы, созданные из исходного кода и патчей, если таковые имелись, библиотеки и метаданные. Менеджер пакетов RPM использует эти метаданные для проверки наличия необходимых пакетов из списка зависимостей, исполнения инструкций по установке файлов и сохранения общей информации о пакете у себя в базе.

[[rpm-packaging-tools]]
== Подготовка к сборке RPM-пакетов

Пакет ``rpmdevtools``, установленный на этапе xref:prerequisites[Необходимые пакеты], предоставляет несколько утилит, упрощающие подготовку к сборке RPM-пакетов. Чтобы перечислить эти утилиты, выполните в консоли следующую команду:

[source,bash]
----
$ rpm -ql rpmdevtools | grep bin

----

Для получения дополнительной информации о вышеуказанных утилитах см. их страницы руководства или диалоговые окна справки.

[[rpm-packaging-workspace]]
== Рабочее пространство для сборки RPM-пакетов
Чтобы создать дерево каталогов, которое является рабочей областью сборки RPM-пакетов, используйте утилиту ``rpmdev-setuptree``, или же создайте каталоги вручную, используя утилиту `mkdir`:

[source,bash]
----
$ rpmdev-setuptree

$ tree ~/rpmbuild/
/home/user/rpmbuild/
|-- BUILD
|-- RPMS
|-- SOURCES
|-- SPECS
 -- SRPMS

----

Описание созданных каталогов:

[cols="20%,80%"]
|====
| Каталог | Назначение
| BUILD     | Содержит все файлы, которые появляются при сборке пакета.
| RPMS      | Здесь появляются готовые RPM-пакеты (`.rpm`) в подкаталогах для разных архитектур, например, в подкаталогах``x86_64`` и ``noarch``.
| SOURCES   | Здесь находятся архивы исходного кода и патчи. Утилита ``rpmbuild`` ищет их здесь.
| SPECS     | Здесь хранятся spec-файлы.
| SRPMS     | Здесь находятся пакеты с исходниками (`.src.rpm`).
|====

После создания дерева каталогов перейдём в файл `~/home/.rpmmacros`. В нём содержится следующая информация:

* Месторасположение структуры каталогов для сборки;

* Ключ для подписи пакетов;

* Значение поля _Packager_

[source, bash]

----
%_topdir<------>%homedir/RPM
#%_tmppath<---->%homedir/tmp

# %packager<--->Joe Hacker <joe@email.address>
# %_gpg_name<-->joe@email.address
----

Раскомментируйте поле _Packager_: Впишите своё имя, фамилию и почту. Поле с ключём для подписи Вы заполните позже. О том, как создавать ключи, Вы узнаете в разделе xref:JoinKey[Создание SSH и GPG ключей].

NOTE: Действия, описанные ниже, необходимы для корректного прохождения документации, они обязательны к выполнению! 

Итак, если Вы воспользовались утилитой `rpmdev-setuptree`, а не создали дерево каталогов вручную, обрате внимание на файл `~/home/.rpmmacros`:

[source, bash]

----
%_topdir<------>%homedir/RPM
#%_tmppath<---->%homedir/tmp

%packager<--->Joe Hacker <joe@email.address>
# %_gpg_name<-->joe@email.address

%__arch_install_post \
    [ "%{buildarch}" = "noarch" ] || QA_CHECK_RPATHS=1 ; \
    case "${QA_CHECK_RPATHS:-}" in [1yY]*) /usr/lib/rpm/check-rpaths ;; esac \
    /usr/lib/rpm/check-buildroot

----

В файле появилась секция `%__arch_install_post`. Данную секцию необходимо удалить, вернув файл к исходному состоянию, иначе процесс сборки будет завершаться с ошибкой. 

[source, bash]

----
%_topdir<------>%homedir/RPM
#%_tmppath<---->%homedir/tmp

%packager<--->Valentin Sokolov <sova@altlinux.org>
# %_gpg_name<-->joe@email.address
----
