[[patching-software]]
== Программное обеспечение для исправления ошибок

**Patch** - это исходный код, который исправляет другой исходный код. Он отформатирован как __diff__, потому что представляет разницу между двумя версиями текста. Разница создаётся с помощью утилиты ``diff``, которая затем применяется к исходному коду с помощью утилиты http://savannah.gnu.org/projects/patch/[patch].

NOTE: Разработчики программного обеспечения часто используют системы контроля версий, такие как https://git-scm.com/[git], для управления своей кодовой базой. Такие инструменты предоставляют свои собственные методы создания различий или исправления программного обеспечения.

В следующем примере мы создаем исправление из исходного кода с помощью 
``diff``, а затем используем ``patch``. Исправление использует в следующих разделах при создании RPM и работе со .spec-файлом. xref:working-with-spec-files[Работа со SPEC файлами].



[[putting-source-code-into-tarball]]
== Создание Tarball с исходным кодом

В приведенных ниже примерах мы помещаем каждую из трех программ  ``Hello World`` в архив, сжатый с помощью
https://www.gnu.org/software/gzip/[gzip]. Программное обеспечение часто выпускается таким образом, чтобы позже быть упакованным для распространения.

[[using_Make]]
== Make


[[version-control-systems]]
== Система контроля версий

При работе с RPMs желательно использовать 
https://en.wikipedia.org/wiki/Version_control[Системы контроля версий] (VCS), такую как https://git-scm.com/[git], для управления компонентами программного обеспечения, которое мы упаковываем.
Следует отметить, что хранение бинарных файлов в системе контроля версий нецелесообразно, поскольку это резко увеличивает размер исходного репозитория, поскольку эти инструменты разработаны для обработки различий в файлах (часто оптимизированных для текстовых файлов), чему не поддаются бинарные файлы, поэтому обычно сохраняется весь бинарные файл целиком. Существуют некоторые утилиты, популярные среди upstream проектов с открытым исходным кодом, которые решают эту проблему, либо сохраняя SPEC файл, где исходный код находится в VCS (т. е. - он не находится в сжатом архиве для распространения ), либо помещая в VCS только SPEC-файл и патчи и загружается сжатый архив updtream исходного кода  в так называемый «кэш просмотра».

В этом разделе мы рассмотрим два различных варианта использования системы контроля версий 
https://git-scm.com/[git] для управления содержимым, которое в конечном итоге будет преобразовано в пакет RPM. Первый называется https://github.com/dgoodwin/tito[tito],
второй - https://github.com/release-engineering/dist-git[dist-git].

NOTE: Вам нужно будет установить пакет ``git`` в Вашу систему, он понадобится нам для изучения данного раздела.


[[Gear_ALT]]
== Окружение Gear


[[Hasher_ALT]]
== Окружение Hasher
