[[Preparing_program]]
= Подготовка программ 

В этом руководстве представлены три версии программы ``Hello World`` , каждая из которых написана на разных языках программирования. 

**Исходный код ** - это понятные для человека инструкции к компьютеру, в которых описывается, как выполнить вычисления. Исходный код выражается с помощью
[https://ru.wikipedia.org/wiki/Язык_программирования[языка программирования]].


NOTE: Существуют тысячи языков программирования. В этом документе представлены только три из них, но их достаточно для концептуального обзора.

Программа ``Hello World``, написанная на https://ru.wikipedia.org/wiki/Bash[bash]:

``bello``

[source,bash]
----
#!/bin/bash

printf "Hello World\n"

----

``Hello World``, написанная на https://ru.wikipedia.org/wiki/Python[Python]:

``pello.py``

[source,python]
----
#!/usr/bin/env python3

print("Hello World")

----

``Hello World``, написанная на https://ru.wikipedia.org/wiki/Си_(язык_программирования)[C]:

``cello.c``

[source,c]
----
#include <stdio.h>

int main(void) {
    printf("Hello World\n");
    return 0;
}

----

Целью каждой из трех программ является вывод строки ``Hello World`` в консоли.



[[manual-building]]
== Сборка из исходников 

В этом разделе объясняется процесс сборки программ из исходного кода.

* Для исходного кода программ, написанных на компилируемых языках, происходит процесс *компиляции*. Этот процесс различается для разных языков. Полученный в результате сборки код становится *исполняемым*.

* Программы, написанные на языке с прямой интерпретацией вообще не нужно компилировать, они выполняются непосредственно интерпретатором.

* Для программ, написанных  на интерпретируемых языках с компиляцией в байт-код, исходный код компилируется в байт-код, который затем выполняется виртуальной машиной соответствующего языка.


В этом примере демонстрируется процесс преобразования программы ``cello.c``, написанной на языке https://en.wikipedia.org/wiki/C_%28programming_language%29[C] в исполняемый файл.

``cello.c``

[source,c]
----
#include <stdio.h>

int main(void) {
    printf("Hello World\n");
    return 0;
}

----

[[hand-building]]
=== Ручная сборка

Вызовите компилятор
https://en.wikipedia.org/wiki/C_%28programming_language%29[C] из коллекции компиляторов GNU  (https://gcc.gnu.org/[GCC]), чтобы скомпилировать исходный код в бинарный файл:

[source,bash]
----
gcc -g -o cello cello.c

----

Запустите бинарный файл ``cello``.

[source,bash]
----
$ ./cello
Hello World

----

В данном примере был продемонстрирован процесс компиляции программы в исполняемый файл.


=== Автоматическая сборка


Вместо того, чтобы проводить процесс компиляции исходного кода программы вручную, Вы можете автоматизировать сборку. Автоматизация сборки осуществляется путём создания ``Makefile`` и последующим запуском утилиты
http://www.gnu.org/software/make/[GNU ``make``].

Чтобы настроить автоматическую сборку, создайте файл с именем ``Makefile`` в том же каталоге, что и``cello.c``:

``Makefile``

[source,makefile]
----
cello:
        gcc -g -o cello cello.c

clean:
        rm cello

----

Теперь, чтобы собрать программу, просто запустите ``make``:

[source,bash]
----
$ make
make: 'cello' is up to date.

----

Исполняемый файл создан, ``make clean`` удалит его. Затем мы снова запустим ``make``:

[source,bash]
----
$ make clean
rm cello

$ make
gcc -g -o cello cello.c

----

NOTE: Удаление бинарного файла может помочь убедиться, что при последующей сборке программа будет скомпилирована заново и не будет использоваться устаревший бинарный файл. Это может быть особенно полезно, если вы изменили код программы и хотите убедиться, что все изменения были учтены при повторной сборке.

Попытка сборки без изменений исходного кода программы ничего не даст:

[source,bash]
----
$ make
make: 'cello' is up to date.

----

Запустим исполняемый файл:

[source,bash]
----
$ ./cello
Hello World

----

Теперь Вы скомпилировали программу как вручную, так и с помощью инструмента сборки.

=== Интерпретируемый код 

В данном разделе продемонстрирован процесс преобразования исходных текстов программ bello и pello, написанных на интерпретируемых языках python и bash 


[NOTE]
====

В двух приведенных ниже примерах строка ``#!``в верхней части файла называется https://ru.wikipedia.org/wiki/Шебанг_(Unix)[shebang]
и не является частью исходного кода.

https://ru.wikipedia.org/wiki/Шебанг_(Unix)[shebang] позволяет использовать текстовый файл в качестве исполняемого файла: загрузчик системной программы анализирует строку, содержащую *shebang*, чтобы получить путь к бинарному исполняемому файлу, который затем используется в качестве интерпретатора языка программирования.

====

==== Компиляция в байт-код

В этом примере показан процесс трансляции в байт-код программы `pello.py`, написанной на Python, который затем выполняется виртуальной машиной Python.


``pello.py``

[source,python]
----
#!/usr/bin/env python

print("Hello World")

----

Процедура преобразования программ в байт-код различна. Это зависит от языка, виртуальной машины языка, а также инструментов и процессов, используемых этим языком.

NOTE: Программы, написанные на https://www.python.org/[Python] часто транслируются в байт-код, но не так, как описано здесь. Следующая процедура направлена не на то, чтобы соответствовать стандартам сообщества, а на то, чтобы быть простой. Для получения практических рекомендаций по Python см. раздел
https://docs.python.org/2/library/distribution.html[Упаковка и распространение программного обеспечения].

Трансляция `pello.py` в байт-код:

[source,bash]
----
$ python3 -m compileall pello.py

----

В рабочем каталоге создастся подкаталог `pycache`:

[source,bash]
----
$ ls 
pello.py  __pycache__

----

в котором находится скомпилированный в байт-код файл: 

[source,bash]
----
$ ls ./__pycache__
pello.cpython-39.pyc

----

Запустим его: 

[source,bash]
----
$ python3 pello.cpython-39.pyc
Hello world!
----

=== Bash 

