[[Preparing_program]]
= Подготовка программ 

В этом руководстве представлены три версии программы ``Hello World`` , каждая из которых написана на разных языках программирования. Программы, написанные на этих трех разных языках собираются по разному и охватывают три основных варианта использования RPM сборщиком ПО.

[[what-is-source-code]]
== Что такое Исходный код?

**Исходный код ** - это понятные для человека инструкции к компьютеру, в которых описывается, как выполнить вычисления. Исходный код выражается с помощью
[https://ru.wikipedia.org/wiki/Язык_программирования[языка программирования]].


NOTE: Существуют тысячи языков программирования. В этом документе представлены только три из них, но их достаточно для концептуального обзора.

Программа ``Hello World``, написанная на https://www.gnu.org/software/bash/[bash]:

``bello``

[source,bash]
----
#!/bin/bash

printf "Hello World\n"

----

``Hello World``, написанная на https://www.python.org/[Python]:

``pello.py``

[source,python]
----
#!/usr/bin/env python

print("Hello World")

----

``Hello World``, написанная на https://en.wikipedia.org/wiki/C_%28programming_language%29[C]:

``cello.c``

[source,c]
----
#include <stdio.h>

int main(void) {
    printf("Hello World\n");
    return 0;
}

----

Целью каждой из трех программ является вывод строки ``Hello World`` в консоли.



[[manual-building]]
== Сборка из исходников 

В этом разделе объясняется процесс сборки программ из исходного кода.

* Для исходного кода программ, написанных на компилируемых языках, происходит процесс *компиляции*. Этот процесс различается для разных языков. Полученный в результате сборки код становится *исполняемым*.

* Программы, написанные на языке с прямой интерпретацией вообще не нужно компилировать, они выполняются непосредственно интерпретатором.

* Для программ, написанных  на интерпретируемых языках с компиляцией в байт-код, исходный код компилируется в байт-код, который затем выполняется виртуальной машиной соответствующего языка.


В этом примере демонстрируется процесс преобразования программы ``cello.c``, написанной на языке https://en.wikipedia.org/wiki/C_%28programming_language%29[C] в исполняемый файл.

``cello.c``

[source,c]
----
#include <stdio.h>

int main(void) {
    printf("Hello World\n");
    return 0;
}

----

[[hand-building]]
=== Ручная сборка

Вызовите компилятор
[https://en.wikipedia.org/wiki/C_%28programming_language%29[C]] из коллекции компиляторов GNU  (https://gcc.gnu.org/[GCC]), чтобы скомпилировать исходный код в бинарный файл:

[source,bash]
----
gcc -g -o cello cello.c

----

Запустите бинарный файл ``cello``.

[source,bash]
----
$ ./cello
Hello World

----

В данном примере был продемонстирован процесс компиляци программы в исполняемый файл.