[[Why-Package-Software-with-RPM]]
= Введение в пакетные менеджеры

*RPM* — это семейство пакетных менеджеров, применяемых в различных дистрибутивах GNU/Linux, в том числе и в проекте https://www.altlinux.org/Sisyphus[Сизиф] и в дистрибутивах https://www.altlinux.org/Releases[Альт]. Практически каждый крупный проект, использующий RPM, имеет свою версию пакетного менеджера, отличающуюся от остальных.

Различия между представителями семейства RPM выражаются в: ::

* наборе макросов, используемых в .spec-файлах,

* различном поведении RPM при сборке «по умолчанию» — при отсутствии каких-либо указаний в .spec-файлах,

* формате строк зависимостей,

* мелких отличиях в семантике операций (например, в операциях сравнения версий пакетов),

* мелких отличиях в формате файлов.

Для пользователя различия чаще всего заключаются в невозможности поставить «неродной» пакет из-за проблем с зависимостями или из-за формата пакета.

RPM в проекте Сизиф также не является исключением. Основные особенности RPM в Альт и Сизиф от RPM других крупных проектов заключаются в следующем: ::

* обширный набор макросов для упаковки различных типов пакетов,

* отличающееся поведение «по умолчанию» для уменьшения количества шаблонного кода в .spec-файлах,

* наличие механизмов для автоматического поиска межпакетных зависимостей,


* наличие так называемых set-version зависимостей (начиная с `4.0.4-alt98.46` ), обеспечивающих дополнительный контроль за изменением ABI библиотек,

* до `p8` и выпусков `8.x` включительно -- очень древняя версия «базового» RPM (4.0.4), от которого началось развитие ветки RPM в Sisyphus (в Sisyphus и `p9` осуществлён частичный переход на `rpm 4.13`).


[[RPM_Commands]]
== Основные команды RPM

Как узнать информацию о пакете RPM без установки?::

После скачивания пакета можно посмотреть данные о нём перед установкой. Для этого используется *-qip*, чтобы вывести информацию о пакете. 

[source,bash]

----
$ rpm -qip GeoIP-1.5.0-11.el7.x86_64.rpm
----

Вывод:

[source,bash]

----
Name        : GeoIP
Version     : 1.5.0
Release     : 11.el7
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Libraries
Size        : 2905020
License     : LGPLv2+ and GPLv2+ and CC-BY-SA
Signature   : RSA/SHA256, Sun 20 Nov 2016 05:49:19 PM UTC, Key ID 24c6a8a7f4a80eb5
Source RPM  : GeoIP-1.5.0-11.el7.src.rpm
Build Date  : Sat 05 Nov 2016 08:29:17 PM UTC
Build Host  : worker1.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem 
Vendor      : CentOS
URL         : http://www.maxmind.com/app/c
Summary     : Library for country/city/organization to IP address or hostname mapping
Description :
GeoIP is a C library that enables the user to find the country that any IP
address or hostname originates from. It uses a file based database that is
accurate as of June 2007 and can optionally be updated on a weekly
basis by installing the GeoIP-update package. This database simply contains IP
blocks as keys, and countries as values. This database should be more complete
and accurate than using reverse DNS lookups.

This package includes GeoLite data created by MaxMind, available from
http://www.maxmind.com/
----

Как установить RPM пакет?::

Для установки используется параметр *-ivh*.

[source,bash]

----
$ rpm -ivh GeoIP-1.5.0-11.el7.x86_64.rpm
----

Вывод: 

[source,bash]

----
   Preparing...                          ################################# [100%]
        package GeoIP-1.5.0-11.el7.x86_64 is already installed
----


Проверка установки пакета в системе.::

[source,bash]

----
$ rpm -q GeoIP
----

Вывод:
[source,bash]
----
GeoIP-1.5.0-11.el7.x86_64
----

Просмотр файлов определённого пакета, установленного в системе.::

[source,bash]

----
$ rpm -ql GeoIP
----

Вывод:

[source,bash]

----
/etc/GeoIP.conf
/etc/GeoIP.conf.default
/usr/bin/geoiplookup
/usr/bin/geoiplookup6
/usr/bin/geoipupdate
/usr/lib64/libGeoIP.so.1
/usr/lib64/libGeoIP.so.1.5.0
/usr/lib64/libGeoIPUpdate.so.0
/usr/lib64/libGeoIPUpdate.so.0.0.0
/usr/share/GeoIP
/usr/share/GeoIP/GeoIP-initial.dat
/usr/share/GeoIP/GeoIP.dat
/usr/share/GeoIP/GeoIPASNum.dat
/usr/share/GeoIP/GeoIPASNumv6.dat
/usr/share/GeoIP/GeoIPCity.dat
/usr/share/GeoIP/GeoIPCityv6.dat
/usr/share/GeoIP/GeoIPCountry.dat
/usr/share/GeoIP/GeoIPCountryv6.dat
/usr/share/GeoIP/GeoIPv6-initial.dat
...
----

Просмотр недавно установленных пакетов в систему.::

[source,bash]

----
rpm -qa --last|head
----

Вывод:

[source,bash]

----
perl-libintl-1.32-alt1.x86_64                 Вт 20 дек 2022 11:08:34
perl-Git-2.33.5-alt1.noarch                   Вт 20 дек 2022 11:08:34
perl-Error-0.17029-alt1.noarch                Вт 20 дек 2022 11:08:34
git-core-2.33.5-alt1.x86_64                   Вт 20 дек 2022 11:08:34
git-2.33.5-alt1.x86_64                        Вт 20 дек 2022 11:08:34
diffstat-1.64-alt1.x86_64                     Вт 20 дек 2022 11:08:34
perl-TermReadKey-2.38-alt1.1.x86_64           Вт 20 дек 2022 11:08:33
codium-1.72.1.22284-alt1.x86_64               Вт 20 дек 2022 03:33:53
eepm-3.19.4-alt1.noarch                       Вт 20 дек 2022 03:30:55
kernel-modules-virtualbox-un-def-6.1.40-alt1.331600.1.x86_64 Вт 20 дек 2022 03:21:17

----

Поиск определённого пакета в системе.::

Команда *grep* поможет определить, установлен пакет в системе или нет:

[source,bash]

----
$ rpm -qa | grep GeoIP
----

Вывод:

[source,bash]

----
GeoIP-1.5.0-11.el7.x86_64
----

Проверка файла, относящегося к конкретному пакету в системе.::

Предположим, что нужно узнать, к какому конкретному пакету относится файл. Для этого используют команду:

[source,bash]

----
$ rpm -qf /usr/lib64/libGeoIP.so.1.5.0
----

Вывод:

[source,bash]

----
GeoIP-1.5.0-11.el7.x86_64
----


Вывод информации о конкретном пакете.::

Чтобы получить информацию о конкретном пакете, установленного в систему, используем команду:

[source,bash]

----
$ rpm -qi GeoIP
----

Вывод:

[source,bash]

----
Output
Name        : GeoIP
Version     : 1.5.0
Release     : 11.el7
Architecture: x86_64
Install Date: Thu 16 Aug 2018 02:04:09 PM UTC
Group       : Development/Libraries
Size        : 2905020
License     : LGPLv2+ and GPLv2+ and CC-BY-SA
Signature   : RSA/SHA256, Sun 20 Nov 2016 05:49:19 PM UTC, Key ID 24c6a8a7f4a80eb5
Source RPM  : GeoIP-1.5.0-11.el7.src.rpm
Build Date  : Sat 05 Nov 2016 08:29:17 PM UTC
Build Host  : worker1.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem
Vendor      : CentOS
URL         : http://www.maxmind.com/app/c
Summary     : Library for country/city/organization to IP address or hostname mapping
Description :
GeoIP is a C library that enables the user to find the country that any IP
address or hostname originates from. It uses a file based database that is
accurate as of June 2007 and can optionally be updated on a weekly
basis by installing the GeoIP-update package. This database simply contains IP
blocks as keys, and countries as values. This database should be more complete
and accurate than using reverse DNS lookups.

This package includes GeoLite data created by MaxMind, available from http://www.maxmind.com/
----

Обновление пакета.::    

Для обновления определённого пакета используется параметр *-Uvh*.

[source,bash]

----
$ rpm -Uvh GeoIP-1.5.0-11.el7.x86_64.rpm
----

Вывод:

[source,bash]

----
 Preparing...                          ################################# [100%]
 package GeoIP-1.5.0-11.el7.x86_64 is already installed
----
