[[Why-Package-Software-with-RPM]]
= Введение в пакетные менеджеры

*RPM* — это семейство пакетных менеджеров, применяемых в различных дистрибутивах GNU/Linux, в том числе и в проекте https://www.altlinux.org/Sisyphus[Sisyphus] и в дистрибутивах https://www.altlinux.org/Releases[ALT Linux]. Практически каждый крупный проект, использующий RPM, имеет свою версию пакетного менеджера, отличающуюся от остальных.

Различия между представителями семейства RPM выражаются в: ::

* наборе макросов, используемых в .spec-файлах,

* различном поведении RPM при сборке «по умолчанию» — при отсутствии каких-либо указаний в .spec-файлах,

* формате строк зависимостей,

* мелких отличиях в семантике операций (например, в операциях сравнения версий пакетов),

* мелких отличиях в формате файлов.

Для пользователя различия чаще всего заключаются в невозможности поставить «неродной» пакет из-за проблем с зависимостями или из-за формата пакета.

RPM в проекте Sisyphus также не является исключением. Основные особенности RPM в ALT Linux и Sisyphus от RPM других крупных проектов заключаются в следующем: ::

* обширный набор макросов для упаковки различных типов пакетов,

* отличающееся поведение «по умолчанию» для уменьшения количества шаблонного кода в .spec-файлах,

* наличие механизмов для автоматического поиска межпакетных зависимостей,


* наличие так называемых set-version зависимостей (начиная с `4.0.4-alt98.46` ), обеспечивающих дополнительный контроль за изменением ABI библиотек,

* до `p8` и выпусков `8.x` включительно -- очень древняя версия «базового» RPM (4.0.4), от которого началось развитие ветки RPM в Sisyphus (в Sisyphus и `p9` осуществлён частичный переход на `rpm 4.13`).


[[RPM_Commands]]
== Основные команды RPM

Как узнать информацию о пакете RPM без установки?::

После скачивания пакета можно посмотреть данные о нём перед установкой. Для этого используется *-qipoption*, чтобы вывести информацию о пакете. 

[source,bash]

----
$ sudo rpm -qip GeoIP-1.5.0-11.el7.x86_64.rpm
----

Вывод:

[source,bash]

----
Name        : GeoIP
Version     : 1.5.0
Release     : 11.el7
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Libraries
Size        : 2905020
License     : LGPLv2+ and GPLv2+ and CC-BY-SA
Signature   : RSA/SHA256, Sun 20 Nov 2016 05:49:19 PM UTC, Key ID 24c6a8a7f4a80eb5
Source RPM  : GeoIP-1.5.0-11.el7.src.rpm
Build Date  : Sat 05 Nov 2016 08:29:17 PM UTC
Build Host  : worker1.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem 
Vendor      : CentOS
URL         : http://www.maxmind.com/app/c
Summary     : Library for country/city/organization to IP address or hostname mapping
Description :
GeoIP is a C library that enables the user to find the country that any IP
address or hostname originates from. It uses a file based database that is
accurate as of June 2007 and can optionally be updated on a weekly
basis by installing the GeoIP-update package. This database simply contains IP
blocks as keys, and countries as values. This database should be more complete
and accurate than using reverse DNS lookups.

This package includes GeoLite data created by MaxMind, available from
http://www.maxmind.com/
----

Как установить RPM пакет?::

Для установки используется параметр *-ivh*.

[source,bash]

----
$ sudo rpm -ivh GeoIP-1.5.0-11.el7.x86_64.rpm
----

Вывод: 

[source,bash]

----
   Preparing...                          ################################# [100%]
        package GeoIP-1.5.0-11.el7.x86_64 is already installed
----


Проверка установки пакета в системе.::

[source,bash]

----
$ sudo rpm -q GeoIP
----

Вывод:
[source,bash]
----
GeoIP-1.5.0-11.el7.x86_64
----

Просмотр файлов определённого пакета, установленного в системе.::

[source,bash]

----
$ sudo rpm -ql GeoIP
----

Вывод:

[source,bash]

----
/etc/GeoIP.conf
/etc/GeoIP.conf.default
/usr/bin/geoiplookup
/usr/bin/geoiplookup6
/usr/bin/geoipupdate
/usr/lib64/libGeoIP.so.1
/usr/lib64/libGeoIP.so.1.5.0
/usr/lib64/libGeoIPUpdate.so.0
/usr/lib64/libGeoIPUpdate.so.0.0.0
/usr/share/GeoIP
/usr/share/GeoIP/GeoIP-initial.dat
/usr/share/GeoIP/GeoIP.dat
/usr/share/GeoIP/GeoIPASNum.dat
/usr/share/GeoIP/GeoIPASNumv6.dat
/usr/share/GeoIP/GeoIPCity.dat
/usr/share/GeoIP/GeoIPCityv6.dat
/usr/share/GeoIP/GeoIPCountry.dat
/usr/share/GeoIP/GeoIPCountryv6.dat
/usr/share/GeoIP/GeoIPv6-initial.dat
...
----

Просмотр недавно установленных пакетов в систему.::

[source,bash]

----
rpm -qa --last
----

Вывод:

[source,bash]

----
hasher-priv-1.6.1-alt1.x86_64                 Ср 19 окт 2022 13:37:15
hasher-1.4.8-alt1.noarch                      Ср 19 окт 2022 13:37:15
gpg-pubkey-cc5fdb34-540dae43                  Ср 19 окт 2022 04:02:03
bello-0.1-alt1.noarch                         Ср 28 сен 2022 18:35:35
cdrdao-1.2.4-alt1.x86_64                      Пн 19 сен 2022 18:09:38
mutt-default-2.1.1.0.3.g6c0f75cca-alt1.x86_64 Вт 06 сен 2022 20:28:09
mutt-2.1.1.0.3.g6c0f75cca-alt1.x86_64         Вт 06 сен 2022 20:28:09
postfix-3.6.2-alt1.x86_64                     Вт 06 сен 2022 20:28:06
sendmail-common-1.7-alt3.noarch               Вт 06 сен 2022 20:28:05
postfix-control-1.6.1-alt1.noarch             Вт 06 сен 2022 20:28:05
----

Поиск определённого пакета в системе.::

Команда *grep* поможет определить, установлен пакет в системе или нет:

[source,bash]

----
$ sudo rpm -qa | grep GeoIP
----

Вывод:

[source,bash]

----
GeoIP-1.5.0-11.el7.x86_64
----

Проверка файла, относящегося к конкретному пакету в системе.::

Предположим, что нужно узнать, к какому конкретному пакету относится файл. Для этого используют команду:

[source,bash]

----
$ sudo rpm -qf /usr/lib64/libGeoIP.so.1.5.0
----

Вывод:

[source,bash]

----
GeoIP-1.5.0-11.el7.x86_64
----


Вывод информации о конкретном пакете.::

Чтобы получить информацию о конкретном пакете, установленного в систему, используем команду:

[source,bash]

----
$ sudo rpm -qi GeoIP
----

Вывод:

[source,bash]

----
Output
Name        : GeoIP
Version     : 1.5.0
Release     : 11.el7
Architecture: x86_64
Install Date: Thu 16 Aug 2018 02:04:09 PM UTC
Group       : Development/Libraries
Size        : 2905020
License     : LGPLv2+ and GPLv2+ and CC-BY-SA
Signature   : RSA/SHA256, Sun 20 Nov 2016 05:49:19 PM UTC, Key ID 24c6a8a7f4a80eb5
Source RPM  : GeoIP-1.5.0-11.el7.src.rpm
Build Date  : Sat 05 Nov 2016 08:29:17 PM UTC
Build Host  : worker1.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem
Vendor      : CentOS
URL         : http://www.maxmind.com/app/c
Summary     : Library for country/city/organization to IP address or hostname mapping
Description :
GeoIP is a C library that enables the user to find the country that any IP
address or hostname originates from. It uses a file based database that is
accurate as of June 2007 and can optionally be updated on a weekly
basis by installing the GeoIP-update package. This database simply contains IP
blocks as keys, and countries as values. This database should be more complete
and accurate than using reverse DNS lookups.

This package includes GeoLite data created by MaxMind, available from http://www.maxmind.com/
----

Обновление пакета.::    

Для обновления определённого пакета используется параметр *-Uvh*.

[source,bash]

----
$ sudo rpm -Uvh GeoIP-1.5.0-11.el7.x86_64.rpm
----

Вывод:

[source,bash]

----
 Preparing...                          ################################# [100%]
 package GeoIP-1.5.0-11.el7.x86_64 is already installed
----
