[[Why-Package-Software-with-RPM]]
= Введение в пакетные менеджеры

*RPM* — это семейство пакетных менеджеров, применяемых в различных дистрибутивах GNU/Linux, в том числе и в проекте https://www.altlinux.org/Sisyphus[Sisyphus] и в дистрибутивах https://www.altlinux.org/Releases[ALT Linux]. Практически каждый крупный проект, использующий RPM, имеет свою версию пакетного менеджера, отличающуюся от остальных.

Различия между представителями семейства RPM выражаются в: ::

* наборе макросов, используемых в .spec-файлах,

* различном поведении RPM при сборке «по умолчанию» — при отсутствии каких-либо указаний в .spec-файлах,

* формате строк зависимостей,

* мелких отличиях в семантике операций (например, в операциях сравнения версий пакетов),

* мелких отличиях в формате файлов.

Для пользователя различия чаще всего заключаются в невозможности поставить «неродной» пакет из-за проблем с зависимостями или из-за формата пакета.

RPM в проекте Sisyphus также не является исключением. Основные особенности RPM в ALT Linux и Sisyphus от RPM других крупных проектов заключаются в следующем: ::

* обширный набор макросов для упаковки различных типов пакетов,

* отличающееся поведение «по умолчанию» для уменьшения количества шаблонного кода в .spec-файлах,

* наличие механизмов для автоматического поиска межпакетных зависимостей,


* наличие так называемых set-version зависимостей (начиная с `4.0.4-alt98.46` ), обеспечивающих дополнительный контроль за изменением ABI библиотек,

* до `p8` и выпусков `8.x` включительно -- очень древняя версия «базового» RPM (4.0.4), от которого началось развитие ветки RPM в Sisyphus (в Sisyphus и `p9` осуществлён частичный переход на `rpm 4.13`).


Многие поставщики программного обеспечения распространяют своё программное обеспечение через обычный архив (например, `tarball`). Однако, упаковка программного обеспечения в пакеты RPM имеет ряд преимуществ.

С помощью RPM пользователь может:

Устанавливать, переустанавливать, удалять, обновлять и проверять пакеты::
Пользователи могут использовать стандартные средства управления пакетами для установки, переустановки, удаления, обновления и проверки ваших пакетов RPM.
Использовать базу данных установленных пакетов для запроса и проверки пакетов::
Поскольку RPM поддерживает базу данных установленных пакетов и их файлов, пользователи могут легко запрашивать и проверять пакеты в своей системе.
Использовать метаданные для описания пакетов, инструкций по их установке и т. д.::
Каждый пакет RPM содержит метаданные, описывающие компоненты пакета, версию, выпуск, размер, URL-адрес проекта, инструкции по установке и так далее.
Упаковывать нетронутые исходные коды программного обеспечения в исходные и бинарные пакеты::
RPM позволяет брать нетронутые исходные коды программного обеспечения и упаковывать их в исходные и бинарные пакеты. В исходных пакетах у Вас есть первозданные исходные тексты вместе с любыми использованными patch-ами, а также полные инструкции по сборке. Такая конструкция облегчает обслуживание пакетов по мере выпуска новых версий ПО.
Установить цифровую подпись упаковки::
Используя ключ подписи GPG, Вы можете подписать пакет цифровой подписью, чтобы пользователи могли проверить подлинность упаковки.
